/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>
int main() {
    // Allocate and initialize the png_struct
    png_struct *png = (png_struct *)calloc(1, sizeof(png_struct));

    // Minimal row buffer so that sp = row_buf + 1 points at end-of-buffer
    // Accessing sp[0] / sp[1] will be out-of-bounds.
    const size_t row_buf_size = 1;  // concrete size as required
    png->row_buf = (png_byte *)malloc(row_buf_size);
    memset(png->row_buf, 0xAA, row_buf_size);

    // Set other fields (values are not critical for this harness path)
    png->transformed_pixel_depth = 8;  // typical 8-bit depth
    png->width = 1;                    // row_width
    png->pass = 0;                     // any pass

    // Destination buffer (also small); dp[1] would also be OOB
    png_byte *dp = (png_byte *)malloc(1);
    memset(dp, 0xAA, 1);

    // display flag arbitrary
    int display = 1;

    // Call the target function directly
    png_combine_row(png, dp, display);

    return 0;
}
