#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>

#ifndef READ_PORT
#define READ_PORT 0
#endif
#ifndef WRITE_PORT
#define WRITE_PORT 1
#endif

/* Mirror minimal layout from harness/pex-common.c */
struct pex_funcs { int dummy; };
struct pex_obj {
    int next_input;
    const struct pex_funcs *funcs;
};

/* Entry prototype */
extern const char * pex_run(struct pex_obj *obj, int flags, const char *executable,
                            char * const * argv, const char *orig_outname,
                            const char *errname, int *err);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    struct pex_obj *obj = (struct pex_obj *)calloc(1, sizeof(struct pex_obj));

    int flags; { memcpy(&flags, fuzz_data + 0, 4); }

    const char *executable = NULL;
    char * const *argv = NULL;
    const char *orig_outname = NULL;
    const char *errname = NULL;
    int err = 0;

    pex_run(obj, flags, executable, argv, orig_outname, errname, &err);
    return 0;
}
