/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int main() {
    // Allocate dummy objects; harness entry is a pass-through so these won't be dereferenced
    bfd *abfd = (bfd*)calloc(1, 64);
    struct bfd_link_info *info = (struct bfd_link_info*)calloc(1, sizeof(struct bfd_link_info));

    // Make fields symbolic in case stubs/key paths inspect them later
    { /* replay: concrete values for "info" (4 bytes) */
    static const unsigned char info_data[] = {0x00, 0x00, 0x00, 0x00};
    memcpy(info, info_data, (sizeof(*info)) < 4 ? (sizeof(*info)) : 4);
  };

    // Call entry function to reach the vulnerable dereference in write_dwarf_eh_frame_hdr
    _bfd_elf_write_section_eh_frame_hdr(abfd, info);
    return 0;
}
