/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Prototype from harness */
bool bfd_cache_close(bfd *abfd);

int main() {
    // Allocate concrete bfd object
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));

    // Make iovec pointer symbolic so the compare reads the field
    const struct bfd_iovec *sym_iovec;
    { /* replay: concrete values for "abfd_iovec" (8 bytes) */
    static const unsigned char abfd_iovec_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(&sym_iovec, abfd_iovec_data, (sizeof(sym_iovec)) < 8 ? (sizeof(sym_iovec)) : 8);
  };
    abfd->iovec = sym_iovec;

    // Optional: give iostream a non-NULL allocation (not required here)
    void *io = malloc(8);
    { /* replay: concrete values for "iostream_bytes" (8 bytes) */
    static const unsigned char iostream_bytes_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(io, iostream_bytes_data, (8) < 8 ? (8) : 8);
  };
    abfd->iostream = io;

    // WMI-2/UAF pattern: free the bfd object, then use it in bfd_cache_close
    free(abfd);

    // Use-after-free: dereference of abfd->iovec in _bfd_cache_close_unlocked
    (void)bfd_cache_close(abfd);

    return 0;
}
