/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

int main() {
    // Allocate concrete structs using harness types
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    png_info *info_ptr = (png_info*)malloc(sizeof(*info_ptr));

    // Initialize fields symbolically (not strictly needed for UAF path)
    if (info_ptr) {
        memset(info_ptr, 0xAA, sizeof(*info_ptr));
    }

    // WMI-2/UAF setup: free the info_ptr to create a stale reference before use
    free(info_ptr);

    // Call entry; our harness entry is a direct pass-through (no guards)
    png_write_info(png_ptr, (const png_info*)info_ptr);

    return 0;
}
