/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdint.h>

/* Minimal local typedefs matching harness */
typedef unsigned char png_byte;
typedef uint32_t png_uint_32;
typedef struct { int dummy; } png_struct;

/* Entry prototype (matches harness) */
void png_write_iCCP(png_struct *png_ptr, const char *name,
                    const png_byte *profile, png_uint_32 profile_len);

int main() {
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    const char *name = NULL;

    // Trigger the vulnerable read: null profile, zero length
    const png_byte *profile = (const png_byte*)0;
    png_uint_32 profile_len = 0;

    png_write_iCCP(png_ptr, name, profile, profile_len);
    return 0;
}
