/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

/* Entry function prototype from harness */
bool bfd_elf_link_add_symbols(bfd *abfd, struct bfd_link_info *info);

int main(void) {
    /* Allocate an opaque bfd object; it's never dereferenced in the harness */
    void *abfd_mem = malloc(64);
    bfd *abfd = (bfd *)abfd_mem;

    /* Allocate/link info with real type from harness_types.h */
    struct bfd_link_info *info = (struct bfd_link_info *)malloc(sizeof(*info));
    if (!info) return 0;

    /* Optionally keep them symbolic to maximize exploration */
    { /* replay: concrete values for "info" (4 bytes) */
    static const unsigned char info_data[] = {0x00, 0x00, 0x00, 0x00};
    memcpy(info, info_data, (sizeof(*info)) < 4 ? (sizeof(*info)) : 4);
  };

    /* Direct call to entry */
    (void)bfd_elf_link_add_symbols(abfd, info);
    return 0;
}
