/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

/* Declare needed runtime/klee symbols without including system headers. */
extern void *calloc(unsigned long nmemb, unsigned long size);
/* klee decl removed */
/* klee decl removed */

/* Local copies matching harness/hash.c */
struct bfd_hash_entry {
  struct bfd_hash_entry *next;
  const char *string;
  unsigned long hash;
};

struct bfd_hash_table {
  struct bfd_hash_entry **table;
  struct bfd_hash_entry *(*newfunc)(struct bfd_hash_entry *, struct bfd_hash_table *, const char *);
  void *memory;
  unsigned int size;
  unsigned int count;
  unsigned int entsize;
  unsigned int frozen:1;
};

extern struct bfd_hash_entry * bfd_hash_insert (struct bfd_hash_table *table, const char *string, unsigned long hash);

int main() {
    struct bfd_hash_table *table = (struct bfd_hash_table *)calloc(1ul, (unsigned long)sizeof(struct bfd_hash_table));
    if (!table) return 0;

    /* Make size symbolic and force n >= last prime to push low one-past-end
       and dereference *low out-of-bounds in higher_prime_number. */
    unsigned int n;
    { /* replay: concrete values for "table_size" (4 bytes) */
    static const unsigned char table_size_data[] = {0xfb, 0xff, 0xff, 0xff};
    memcpy(&n, table_size_data, (sizeof(n)) < 4 ? (sizeof(n)) : 4);
  };

    table->size = n;

    (void)bfd_hash_insert(table, "x", 0ul);
    return 0;
}
