#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

// Define the extern globals declared in harness/elflink.c
const char *g_name;
Elf_Internal_Sym *g_sym;
asection *g_psec;
bfd_vma g_value;
struct elf_link_hash_entry *g_sym_hash;
bfd *g_oldbfd;
bool g_old_weak;
unsigned int g_old_alignment;
bool g_skip;
bfd *g_override;
bool g_type_change_ok;
bool g_size_change_ok;
bool g_matched;

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 1) return 0;
    // Allocate concrete objects for parameters
    bfd *abfd = (bfd*)calloc(1, sizeof(bfd));
    struct bfd_link_info *info = (struct bfd_link_info*)calloc(1, sizeof(struct bfd_link_info));

    // Symbol struct with at least st_info field
    g_sym = (Elf_Internal_Sym*)calloc(1, sizeof(Elf_Internal_Sym));
    // Make st_info symbolic (not required to reach, but good overapprox)
    { memcpy(&g_sym->st_info, fuzz_data + 0, 1); }

    // Section object (not used on path, but must be valid)
    g_psec = (asection*)calloc(1, sizeof(asection));
    g_psec->flags = 0;

    // Initialize remaining globals
    g_name = "sym";              // any non-NULL string
    g_value = 0;
    g_sym_hash = NULL;
    g_oldbfd = NULL;
    g_old_weak = 0;
    g_old_alignment = 0;
    g_skip = 0;
    g_override = NULL;
    g_type_change_ok = 0;
    g_size_change_ok = 0;
    g_matched = 0;

    // Call entry: pass-through to vulnerable function
    (void)bfd_elf_link_add_symbols(abfd, info);
    return 0;
}
