#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Prototypes from harness */
extern bool bfd_check_format (bfd *abfd, bfd_format format);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    // Allocate a concrete bfd object and make its contents symbolic
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    if (!abfd) return 1;

    // Make the relevant field symbolic (read in the vulnerable condition)
    { memcpy(&abfd->target_defaulted, fuzz_data + 0, 4); }

    // Call entry function (direct pass-through to vulnerable function)
    bfd_format format = 0; // value is irrelevant here
    (void)bfd_check_format(abfd, format);

    return 0;
}
