/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

// Decls from harness
void xmlSAX2Characters(void *ctx, const xmlChar *ch, int len);

int main() {
    // Allocate parser context and nodes
    xmlParserCtxtPtr ctxt = (xmlParserCtxtPtr)calloc(1, sizeof(xmlParserCtxt));
    if (!ctxt) return 0;

    xmlNodePtr parent = (xmlNodePtr)calloc(1, sizeof(xmlNode));
    xmlNodePtr last = (xmlNodePtr)calloc(1, sizeof(xmlNode));
    if (!parent || !last) return 0;

    // Link nodes: ctxt->node->last = last
    ctxt->node = parent;
    parent->last = last;

    // Prepare content buffer
    const int capacity = 64; // concrete size
    last->content = (xmlChar*)malloc(capacity);
    if (!last->content) return 0;

    // Initialize context sizes so that newSize == capacity (OOB on terminator write)
    ctxt->nodemem = capacity;   // capacity
    ctxt->nodelen = capacity;   // oldSize

    // ch buffer (even though len == 0, allocate a valid pointer)
    xmlChar *ch = (xmlChar*)malloc(16);
    if (!ch) return 0;
    { /* replay: concrete values for "ch_buf" (16 bytes) */
  static const unsigned char ch_buf_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(ch, ch_buf_data, (16) < 16 ? (16) : 16);
};

    int len = 0; // Force newSize = oldSize + len == capacity

    // Call entry
    xmlSAX2Characters((void*)ctxt, ch, len);

    return 0;
}
