/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int main() {
    // Allocate the target struct concretely
    struct elf_strtab_hash *tab = (struct elf_strtab_hash *)malloc(sizeof(struct elf_strtab_hash));
    if (!tab) return 0;

    // Initialize fields symbolically (size is read in the vulnerable statement)
    { /* replay: concrete values for "tab_size" (8 bytes) */
    static const unsigned char tab_size_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(&tab->size, tab_size_data, (sizeof(tab->size)) < 8 ? (sizeof(tab->size)) : 8);
  };

    // Create a UAF scenario: free the object, then pass stale pointer
    free(tab);

    // Call entry/vulnerable function directly (pass-through)
    _bfd_elf_strtab_finalize(tab);

    return 0;
}
