/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

int main() {
    // Phase 1: allocate an objalloc, then free it to create a stale pointer
    struct objalloc *o = (struct objalloc *)malloc(sizeof(struct objalloc));
    if (!o) return 0;
    // Initialize to avoid undefined bytes (not strictly needed for the sink reachability)
    o->chunks = NULL;

    struct objalloc *stale = o;
    free(o);  // stale now points to freed memory

    // Phase 2 (WMI-2): reclaim the freed region with an object of the same size but different logical type
    // This commonly returns the same address; if so, reading stale->chunks leaks the new contents.
    struct objalloc *reclaimed = (struct objalloc *)malloc(sizeof(struct objalloc));
    if (!reclaimed) return 0;
    // Make the reclaimed memory attacker-controlled/symbolic
    { /* replay: concrete values for "reclaimed_objalloc_bytes" (8 bytes) */
    static const unsigned char reclaimed_objalloc_bytes_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(reclaimed, reclaimed_objalloc_bytes_data, (sizeof(*reclaimed)) < 8 ? (sizeof(*reclaimed)) : 8);
  };

    // Call entry (pass-through to vulnerable statement). This will either:
    //  - read through a freed pointer (UAF) if not reclaimed to same addr, causing .free.err, or
    //  - read type-confused contents if reclaimed to same addr, then hit the universal sink assertion.
    objalloc_free(stale);
    return 0;
}
