#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

int entry_func(double *dp);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    // Allocate an undersized buffer: fewer than 8 bytes to trigger cp[7] OOB
    char *buf = (char *)malloc(4);
    if (!buf) return 0;
    { memcpy(buf, fuzz_data + 0, 4); }

    // Cast to double* as expected by entry_func/TIFFSwabDouble
    double *dp = (double *)buf;

    // Direct call into entry function (which pass-through calls TIFFSwabDouble)
    return entry_func(dp);
}
