#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

typedef unsigned char xmlChar;
typedef int xmlParserErrors;

typedef struct _xmlSchemaAbstractCtxt { int dummy; } *xmlSchemaAbstractCtxtPtr;
typedef struct _xmlNode { int dummy; } *xmlNodePtr;
typedef struct _xmlSchemaType { int type; } *xmlSchemaTypePtr;

int xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                            xmlParserErrors error,
                            xmlNodePtr node,
                            xmlSchemaTypePtr type,
                            const char *message,
                            int nbval,
                            int nbneg,
                            xmlChar **values);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 70) return 0;
    // Allocate concrete objects for parameters
    xmlSchemaAbstractCtxtPtr actxt = (xmlSchemaAbstractCtxtPtr)calloc(1, sizeof(struct _xmlSchemaAbstractCtxt));
    xmlNodePtr node = (xmlNodePtr)calloc(1, sizeof(struct _xmlNode));
    xmlSchemaTypePtr type = (xmlSchemaTypePtr)calloc(1, sizeof(struct _xmlSchemaType));

    // Symbolic message buffer
    char *message = (char *)malloc(64);
    { memcpy(message, fuzz_data + 0, 64); }

    // Symbolic nbval to steer index; allow OOB vs array size 4
    int nbval;
    { memcpy(&nbval, fuzz_data + 64, 4); }
    
    

    int nbneg = 0;
    xmlParserErrors error = 0;

    // Prepare values array with small concrete size
    const size_t arr_sz = 4;
    xmlChar **values = (xmlChar **)malloc(arr_sz * sizeof(xmlChar *));
    for (size_t i = 0; i < arr_sz; i++) {
        values[i] = (xmlChar *)malloc(2);
        { memcpy(values[i], fuzz_data + 68, 2); }
    }

    // Direct call to entry function
    xmlSchemaComplexTypeErr(actxt, error, node, type, message, nbval, nbneg, values);
    return 0;
}
