#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* Minimal sliced harness for xmlWalkRemoveRef */

/* Minimal type preamble to satisfy struct layouts used */
typedef unsigned char xmlChar;
typedef int xmlElementType;
typedef int xmlAttributeType;

typedef struct _xmlNode xmlNode;
typedef struct _xmlAttr xmlAttr;
typedef struct _xmlDoc xmlDoc;
typedef struct _xmlNs xmlNs;

typedef xmlNode *xmlNodePtr;
typedef xmlAttr *xmlAttrPtr;

typedef struct _xmlList xmlList;
typedef xmlList *xmlListPtr;

/* xmlRef definition (excerpt) */
struct _xmlRef {
    struct _xmlRef *next;           /* XML_DEPRECATED_MEMBER stripped */
    const xmlChar  *value;          /* XML_DEPRECATED_MEMBER stripped */
    xmlAttr        *attr;           /* XML_DEPRECATED_MEMBER stripped */
    const xmlChar  *name;           /* XML_DEPRECATED_MEMBER stripped */
    int             lineno;         /* XML_DEPRECATED_MEMBER stripped */
};

typedef struct _xmlRef xmlRef;
typedef xmlRef *xmlRefPtr;

/* xmlAttr definition (minimal fields, keep as opaque layout) */
struct _xmlAttr {
    void           *_private;
    xmlElementType  type;
    const xmlChar  *name;
    xmlNode        *children;
    xmlNode        *last;
    xmlNode        *parent;
    xmlAttr        *next;
    xmlAttr        *prev;
    xmlDoc         *doc;
    xmlNs          *ns;
    xmlAttributeType atype;
    void           *psvi;
    void           *id; /* XML_DEPRECATED_MEMBER stripped */
};

/* xmlRemoveMemo (from source) */
typedef struct xmlRemoveMemo_t {
    xmlListPtr l;
    xmlAttrPtr ap;
} xmlRemoveMemo;

typedef xmlRemoveMemo *xmlRemoveMemoPtr;

/* Forward decl for external used on the path */

/* Vulnerable function — keep exact vulnerable statement line, then universal sink assertion */
static int
