/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stddef.h>

/* Minimal local type defs matching fields used by xmlWalkRemoveRef */
typedef struct _xmlAttr { int dummy; } *xmlAttrPtr;

typedef struct _xmlRef {
    xmlAttrPtr attr;  // first field used in entry preconditions
} *xmlRefPtr;

typedef struct _xmlList { int dummy; } *xmlListPtr;

typedef struct _xmlRemoveMemo {
    xmlAttrPtr ap;    // accessed as ((xmlRemoveMemoPtr)user)->ap
    xmlListPtr l;     // accessed as ((xmlRemoveMemoPtr)user)->l
} *xmlRemoveMemoPtr;

/* Prototype from harness */
int xmlWalkRemoveRef(const void *data, void *user);

/* Minimal libc prototypes */
extern void *calloc(size_t, size_t);

int main(void) {
    // Allocate and initialize xmlRef and its attr
    xmlRefPtr ref = (xmlRefPtr)calloc(1, sizeof(*ref));
    if (!ref) return 0;

    xmlAttrPtr attr = (xmlAttrPtr)calloc(1, sizeof(*attr));
    if (!attr) return 0;
    ref->attr = attr;  // satisfy ((xmlRefPtr)data)->attr

    // Allocate user memo with list and attribute pointer
    xmlRemoveMemoPtr memo = (xmlRemoveMemoPtr)calloc(1, sizeof(*memo));
    if (!memo) return 0;

    xmlListPtr lst = (xmlListPtr)calloc(1, sizeof(*lst));
    if (!lst) return 0;

    memo->ap = attr;   // satisfy ((xmlRemoveMemoPtr)user)->ap
    memo->l  = lst;    // satisfy ((xmlRemoveMemoPtr)user)->l

    // Call entry/vulnerable function directly
    xmlWalkRemoveRef((const void *)ref, (void *)memo);

    return 0;
}
