#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

extern int UTF16BEToUTF8(void *vctxt,
                         unsigned char *out, int *outlen,
                         const unsigned char *in, int *inlen,
                         int flush);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 17) return 0;
    // Intentionally small input buffer (1 byte) while claiming inlen=2 to trigger in[1] OOB
    unsigned char *in = (unsigned char *)malloc(1);
    if (!in) return 0;
    { memcpy(in, fuzz_data + 0, 1); }

    // Output buffer: small but concrete
    unsigned char outbuf[16];
    { memcpy(outbuf, fuzz_data + 1, 16); }

    int inlen = 2;   // Even length makes inend = in + 2 and enters loop once
    int outlen = 16; // Enough space for single-byte/2-byte encodings

    (void)UTF16BEToUTF8(NULL, outbuf, &outlen, in, &inlen, 0);
    return 0;
}
