/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>

static int foreach_cb(splay_tree_node node, void *data) {
    int ret;
    memset(&ret, 0, sizeof(ret));
    return ret;
}

int main() {
    splay_tree sp = (splay_tree)calloc(1, sizeof(*sp));
    if (!sp) return 0;

    splay_tree_node root = (splay_tree_node)calloc(1, sizeof(*root));
    sp->root = root; // may be NULL; that's okay

    char *data = (char*)malloc(16);
    if (data) { /* replay: concrete values for "data_buf" (16 bytes) */
    static const unsigned char data_buf_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(data, data_buf_data, (16) < 16 ? (16) : 16);
  };

    (void)splay_tree_foreach(sp, foreach_cb, data);
    return 0;
}
