/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

int main() {
    // Concrete allocations
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info*)malloc(sizeof(png_info));

    // Initialize fields used in vulnerable statements
    if (!png_ptr || !info_ptr) return 0;
    info_ptr->channels = 3;   // RGB
    info_ptr->bit_depth = 8;  // 8-bit
    info_ptr->width = 64;     // arbitrary positive width

    // Direct call to entry/vulnerable function
    png_read_transform_info(png_ptr, info_ptr);

    return 0;
}
