#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>

// Minimal local typedefs matching harness signatures
typedef unsigned char xmlChar;
typedef int xmlParserErrors;
typedef struct _xmlNode { int dummy; } *xmlNodePtr;
typedef struct _xmlSchemaType { int type; const xmlChar *targetNamespace; const xmlChar *name; } *xmlSchemaTypePtr;
typedef void* xmlSchemaAbstractCtxtPtr;

// Prototype of target function defined in harness
int xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                            xmlParserErrors error,
                            xmlNodePtr node,
                            xmlSchemaTypePtr type,
                            const char *message,
                            int nbval,
                            int nbneg,
                            xmlChar **values);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 52) return 0;
    void *actxt = malloc(64);
    xmlNodePtr node = (xmlNodePtr)calloc(1, sizeof(*node));
    xmlSchemaTypePtr type = (xmlSchemaTypePtr)calloc(1, sizeof(*type));
    if (type) {
        type->type = 1;
        type->targetNamespace = (const xmlChar*)"ns";
        type->name = (const xmlChar*)"t";
    }

    char *message = (char*)malloc(32);
    { memcpy(message, fuzz_data + 0, 32); }
    message[31] = '\0';

    xmlChar **values = (xmlChar**)calloc(2, sizeof(xmlChar*));
    values[0] = (xmlChar*)malloc(16);
    { memcpy(values[0], fuzz_data + 32, 16); }

    int error = 0;
    { memcpy(&error, fuzz_data + 48, 4); }
    int nbval = 1;
    int nbneg = 0;

    xmlSchemaComplexTypeErr((xmlSchemaAbstractCtxtPtr)actxt,
                            error,
                            node,
                            type,
                            message,
                            nbval,
                            nbneg,
                            values);
    return 0;
}
