/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stddef.h>
#include <stdint.h>

// Prototypes to avoid pulling in system headers that conflict
extern void *malloc(size_t);
extern void *calloc(size_t, size_t);

// Minimal local replicas matching the harness definitions
typedef uint32_t sha1_uint32;
struct sha1_ctx {
    sha1_uint32 A, B, C, D, E;
    sha1_uint32 total[2];
    sha1_uint32 buflen;
    sha1_uint32 buffer[32];
};

// Entry function prototype (provided by harness/sha1.c)
void *sha1_finish_ctx(struct sha1_ctx *ctx, void *resbuf);

int main() {
    struct sha1_ctx *ctx = (struct sha1_ctx *)calloc(1, sizeof(struct sha1_ctx));
    if (!ctx) return 1;

    // Initialize state words concretely (symbolic not required to reach sink)
    ctx->A = 0x11111111u;
    ctx->B = 0x22222222u;
    ctx->C = 0x33333333u;
    ctx->D = 0x44444444u;
    ctx->E = 0x55555555u;

    // Intentionally too-small result buffer to exercise sink write
    void *resbuf = malloc(1);
    if (!resbuf) return 1;

    // Direct path to vulnerable function via neutralized entry
    sha1_finish_ctx(ctx, resbuf);
    return 0;
}
