#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 64) return 0;
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    struct elf_obj_tdata *tdata = (struct elf_obj_tdata *)calloc(1, sizeof(struct elf_obj_tdata));

    abfd->tdata = tdata;

    void *buf = malloc(64);
    { memcpy(buf, fuzz_data + 0, 64); }
    tdata->symtab_hdr.contents = buf;

    _bfd_elf_free_cached_info(abfd);
    return 0;
}
