/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Minimal local types matching the harness
typedef unsigned char xmlChar;
typedef int xmlParserErrors;
typedef void* xmlSchemaTypePtr;

typedef struct _xmlNode { struct _xmlNode *next; } xmlNode, *xmlNodePtr;

// Entry prototype from harness
void xmlSchemaComplexTypeErr(void* actxt,
                             xmlParserErrors error,
                             xmlNodePtr node,
                             xmlSchemaTypePtr type,
                             const char *message,
                             int nbval,
                             int nbneg,
                             xmlChar **values);

int main() {
    void *actxt = calloc(1, 64);

    // Allocate a node and its next pointer target concretely
    xmlNode *node = (xmlNode *)calloc(1, sizeof(xmlNode));
    xmlNode *next = (xmlNode *)calloc(1, sizeof(xmlNode));

    // Make the next pointer symbolic (value), but keep it within allocated objects if used
    { /* replay: concrete values for "next_ptr" (8 bytes) */
  static const unsigned char next_ptr_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(&next, next_ptr_data, (sizeof(next)) < 8 ? (sizeof(next)) : 8);
};
    // Ensure node itself is valid and assign whatever next KLEE chooses
    node->next = next;

    xmlSchemaComplexTypeErr(actxt, 0, (xmlNodePtr)node, (xmlSchemaTypePtr)0, (const char*)0, 0, 0, (xmlChar**)0);
    return 0;
}
