/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

int entry_func(double *dp);

int main() {
    // Allocate an undersized buffer: fewer than 8 bytes to trigger cp[7] OOB
    char *buf = (char *)malloc(4);
    if (!buf) return 0;
    { /* replay: concrete values for "buf" (4 bytes) */
  static const unsigned char buf_data[] = {0x00, 0x00, 0x00, 0x00};
  memcpy(buf, buf_data, (4) < 4 ? (4) : 4);
};

    // Cast to double* as expected by entry_func/TIFFSwabDouble
    double *dp = (double *)buf;

    // Direct call into entry function (which pass-through calls TIFFSwabDouble)
    return entry_func(dp);
}
