/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>
/* Prototypes from harness spine */
void png_destroy_info_struct(const png_struct *png_ptr, png_info **info_ptr_ptr);

int main() {
    // Allocate a valid png_struct (contents not used on our path)
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));

    // Allocate png_info and set fields to reach the eXIf free path
    png_info *info = (png_info*)calloc(1, sizeof(png_info));

    // Ensure PNG_FREE_EXIF bit is set so the block executes
#ifndef PNG_FREE_EXIF
#define PNG_FREE_EXIF 0x00000001u
#endif
    info->free_me = PNG_FREE_EXIF;

    // Provide a non-NULL exif pointer to enter inner 'if (info_ptr->exif)'
    void *exif_buf = malloc(64);
    info->exif = exif_buf;

    // Create a stale reference scenario (WMI-2): free info but keep the pointer around
    // png_destroy_info_struct in our harness will directly pass *info_ptr_ptr to png_free_data
    // which will then read fields from the freed info (UAF read at 'if (info_ptr->exif)')
    png_info *info_ptr = info;   // keep a separate variable for clarity
    free(info);                  // Free the struct to create UAF

    // Set up the double-pointer expected by png_destroy_info_struct
    png_info *info_ptr_copy = info_ptr; // still points to freed memory
    png_info **info_ptr_ptr = &info_ptr_copy;

    // Call entry; our harness directly calls png_free_data
    png_destroy_info_struct(png_ptr, info_ptr_ptr);

    return 0;
}
