/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifndef ATTRIBUTE_UNUSED
#define ATTRIBUTE_UNUSED
#endif

/* Match the entry function signature (return type compatible with int) */
int UTF16BEToUTF8(void *vctxt,
                  unsigned char *out, int *outlen,
                  const unsigned char *in, int *inlen,
                  int flush);

int main() {
    const size_t IN_SIZE = 2;    // intentionally smaller than claimed inlen
    const size_t OUT_SIZE = 16;  // reasonable output buffer

    unsigned char *in = (unsigned char *)malloc(IN_SIZE);
    unsigned char *out = (unsigned char *)malloc(OUT_SIZE);
    if (!in || !out) return 0;

    // Symbolic contents; force first 2 bytes to a high surrogate (big-endian 0xD800)
    { /* replay: concrete values for "in_buf" (2 bytes) */
  static const unsigned char in_buf_data[] = {0x00, 0x00};
  memcpy(in, in_buf_data, (IN_SIZE) < 2 ? (IN_SIZE) : 2);
};
    in[0] = 0xD8;  // high byte
    in[1] = 0x00;  // low byte

    { /* replay: concrete values for "out_buf" (16 bytes) */
  static const unsigned char out_buf_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(out, out_buf_data, (OUT_SIZE) < 16 ? (OUT_SIZE) : 16);
};

    int inlen = 4;               // Claimed available input length (>=4)
    int outlen = (int)OUT_SIZE;  // Output length

    (void)UTF16BEToUTF8(NULL, out, &outlen, in, &inlen, 0);
    return 0;
}
