/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#ifndef PNG_HANDLE_CHUNK_LAST
#define PNG_HANDLE_CHUNK_LAST 8
#endif

typedef unsigned char png_byte;

typedef struct png_struct {
    png_byte *chunk_list;
    unsigned int num_chunk_list;
    int unknown_default;
} png_struct;

void png_set_keep_unknown_chunks(png_struct *png_ptr, int keep,
                                 const png_byte *chunk_list, int num_chunks_in);

int main() {
    png_struct *png = (png_struct*)calloc(1, sizeof(png_struct));

    size_t buf_sz = 4; // smaller than 5 so inlist[4] goes OOB
    png_byte *buf = (png_byte*)malloc(buf_sz);
    if (buf) memset(buf, 0xAA, buf_sz);

    png->chunk_list = buf;     // new_list != NULL
    png->num_chunk_list = 1;   // old_num_chunks = 1 -> loop executes once
    png->unknown_default = 0;

    int keep = 0;
    const png_byte *param_chunk_list = NULL;
    int num_chunks_in = 0;

    png_set_keep_unknown_chunks(png, keep, param_chunk_list, num_chunks_in);

    return 0;
}
