/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

/* Signatures from harness */
void bfd_sprintf_vma (bfd *abfd, char *buf, bfd_vma value);

int main() {
    // Allocate a bfd object and backend data
    bfd *abfd = (bfd *)malloc(sizeof(bfd));
    if (!abfd) return 0;

    struct elf_backend_data *bed = (struct elf_backend_data *)malloc(sizeof(struct elf_backend_data));
    struct elf_size_info *siz = (struct elf_size_info *)malloc(sizeof(struct elf_size_info));
    if (!bed || !siz) return 0;

    // Make class symbolic to overapproximate (not strictly needed for UAF)
    { /* replay: concrete values for "elfclass" (4 bytes) */
    static const unsigned char elfclass_data[] = {0x00, 0x00, 0x00, 0x00};
    memcpy(&siz->elfclass, elfclass_data, (sizeof(siz->elfclass)) < 4 ? (sizeof(siz->elfclass)) : 4);
  };

    bed->s = siz;
    abfd->xvec = bed;  // set cross-pointer so stub can read it

    // Prepare output buffer and value (not used by our neutralized entry)
    char buf[64];
    memset(buf, 0, sizeof(buf));
    bfd_vma value = 0;

    // UAF setup: free the backend data so is32bit dereferences a freed pointer
    free(bed);

    // Call entry; it will directly call is32bit -> get_elf_backend_data(abfd)
    // which returns the stale `bed` pointer; dereference at bed->s->elfclass
    bfd_sprintf_vma((bfd *)abfd, buf, value);

    return 0;
}
