/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
int main() {
    // Allocate a non-NULL png_struct; it is not dereferenced in the target.
    png_struct *png_ptr = (png_struct *)calloc(1, sizeof(png_struct));

    // Allocate a png_info, then free it to create a dangling pointer.
    png_info *info_ptr = (png_info *)malloc(sizeof(png_info));

    // Initialize fields (optional) before free; not required to trigger UAF
    if (info_ptr) {
        // Make contents symbolic to overapproximate real scenarios
        memset(info_ptr, 0xAA, sizeof(*info_ptr));
        // Hint: these values would normally pass the guards, but deref happens on freed ptr
        // info_ptr->valid |= PNG_INFO_oFFs; // can't refer to macro here; not needed
        // info_ptr->offset_unit_type = PNG_OFFSET_PIXEL;
    }

    // Free to produce a stale pointer; do NOT nullify to simulate bug pattern
    free(info_ptr);

    // Call the entry/vulnerable function with the dangling pointer.
    // The dereference in the 'if ((info_ptr->valid & PNG_INFO_oFFs) != 0)' triggers UAF.
    (void)png_get_x_offset_pixels(png_ptr, info_ptr);

    // Clean up png_ptr to avoid leaks in harness context (not strictly necessary)
    free(png_ptr);
    return 0;
}
