/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

/* declare entry from harness */
void htmlParseElement(htmlParserCtxt *ctxt);

int main() {
    /* Allocate parser context and input */
    htmlParserCtxt *ctxt = (htmlParserCtxt *)calloc(1, sizeof(*ctxt));
    xmlParserInput *input = (xmlParserInput *)calloc(1, sizeof(*input));

    /* Set up a 1-byte buffer so avail == 1 and cur == '\r' */
    xmlChar *buf = (xmlChar *)malloc(1);
    buf[0] = (xmlChar)('\r');

    /* Wire pointers: cur at start, end one past */
    input->base = buf;
    input->cur  = buf;
    input->end  = buf + 1;
    input->line = 1;
    input->col  = 1;

    ctxt->input = input;
    ctxt->nameNr = 1;         /* arbitrary non-zero */
    ctxt->endCheckState = 0;  /* arbitrary */

    /* Call entry: harness directly calls htmlParseCharData with partial=0 */
    htmlParseElement(ctxt);

    return 0;
}
