/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>
// Prototypes from harness
int png_image_error(png_image *image, const char *error_message);

int main() {
    // Allocate the png_image container
    png_image *img = (png_image*)calloc(1, sizeof(png_image));

    // Allocate the control object that png_image_free dereferences via image->opaque
    struct png_control_def *ctrl = (struct png_control_def*)malloc(sizeof(struct png_control_def));

    // Initialize fields so the vulnerable condition is well-defined
    ctrl->error_buf = NULL; // ensures condition evaluates to compare against NULL

    // Store the pointer, then free it to create a stale reference (UAF scenario)
    img->opaque = ctrl;
    free(ctrl);  // UAF: img->opaque now dangles

    // Prepare an error message (not used in neutralized entry, but harmless)
    char msg[8] = "err";

    // Call entry → directly calls png_image_free, which dereferences freed pointer
    png_image_error(img, msg);

    return 0;
}
