#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Opaque forward decls matching harness signatures
typedef struct _xmlMutex xmlMutex;
void xmlFreeMutex(xmlMutex *tok);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 64) return 0;
    // Allocate a concrete-sized buffer to serve as xmlMutex storage
    const size_t sz = 64; // concrete size, >= sizeof(xmlMutex) in harness
    xmlMutex *tok = (xmlMutex*)malloc(sz);
    if (!tok) return 0;

    // Make the contents symbolic (not the pointer itself)
    { memcpy(tok, fuzz_data + 0, 64); }

    // Free first to create a stale pointer; xmlCleanupMutex will then deref
    free(tok);

    // Call entry; it will pass through to xmlCleanupMutex and dereference
    xmlFreeMutex(tok);
    return 0;
}
