#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* Minimal harness for xmlFreeMutex -> xmlCleanupMutex (threads.c:94)
 * Neutralized entry: direct pass-through to vulnerable function
 * Vulnerable statement kept verbatim, followed by universal sink assertion
 */

/* Force the POSIX branch to include the vulnerable line */
#ifndef HAVE_POSIX_THREADS
#define HAVE_POSIX_THREADS 1
#endif

/* Minimal pthread types to satisfy compilation */
typedef struct { int dummy; } pthread_mutex_t;

/* Forward type from libxml2 */
typedef struct _xmlMutex {
#if HAVE_POSIX_THREADS
    pthread_mutex_t lock;
#else
    int empty;
#endif
} xmlMutex;

/* Decls to match project interface */

