/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>

// Forward declarations matching the harness
typedef struct bfd bfd;
long bfd_get_mtime(bfd *abfd);

int main() {
    // Allocate a concrete buffer for the bfd object
    // Size is arbitrary but concrete; we free it before use
    bfd *abfd = (bfd *)malloc(32);
    if (!abfd) return 0;

    // Free to create stale pointer; bfd_get_mtime will dereference abfd->mtime_set
    free(abfd);

    // Call entry/vulnerable function with freed pointer to trigger UAF at the read
    (void)bfd_get_mtime(abfd);
    return 0;
}
