/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate concrete objects using the harness types
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    png_info *info_ptr = (png_info*)calloc(1, sizeof(*info_ptr));

    // Initialize field then free to create a stale pointer (UAF / WMI-2 setup)
    if (info_ptr) {
        // Fill with symbolic bytes before free to allow arbitrary leak/use patterns
        memset(info_ptr, 0xAA, sizeof(*info_ptr));
        // Now free the object; info_ptr becomes a stale pointer
        free(info_ptr);
    }

    // Optional: reclaim memory to increase chance of same-address reuse (not required for KLEE UAF)
    void *reclaim = malloc(64);
    (void)reclaim;

    // Call entry; it will dereference info_ptr->rendering_intent, causing a use-after-free
    png_write_info(png_ptr, info_ptr);
    return 0;
}
