/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int entry_func(float *fp);

int main() {
    // Allocate a too-small buffer to trigger cp[2] OOB read (needs >=3 bytes)
    size_t sz = 2;  // insufficient for accessing cp[2]
    unsigned char *buf = (unsigned char*)malloc(sz);
    if (!buf) return 0;

    // Make content symbolic (not strictly needed, but standard practice)
    { /* replay: concrete values for "buf_bytes" (2 bytes) */
  static const unsigned char buf_bytes_data[] = {0x00, 0x00};
  memcpy(buf, buf_bytes_data, (sz) < 2 ? (sz) : 2);
};

    // Call entry with a pointer cast to float*
    entry_func((float*)buf);
    return 0;
}
