/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdint.h>

// Minimal redeclaration matching harness function
typedef enum {
    XML_CHAR_ENCODING_NONE = 0,
    XML_CHAR_ENCODING_UTF8,
    XML_CHAR_ENCODING_UTF16LE,
    XML_CHAR_ENCODING_UTF16BE,
    XML_CHAR_ENCODING_UCS4BE,
    XML_CHAR_ENCODING_UCS4LE,
    XML_CHAR_ENCODING_EBCDIC
} xmlCharEncoding;

extern xmlCharEncoding xmlDetectCharEncoding(const unsigned char* in, int len);

int main() {
    unsigned char in[3];
    { /* replay: concrete values for "in_bytes" (3 bytes) */
  static const unsigned char in_bytes_data[] = {0x00, 0x00, 0x00};
  memcpy(in, in_bytes_data, (sizeof(in)) < 3 ? (sizeof(in)) : 3);
};

    int len = 4; // Force the len>=4 path that reads in[0..3]

    // Direct call into vulnerable/entry function
    (void)xmlDetectCharEncoding(in, len);
    return 0;
}
