#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */



// Minimal typedefs to satisfy signatures
typedef unsigned char xmlChar;
typedef int xmlParserErrors;
typedef int xmlSchemaTypeType;

typedef void* xmlSchemaTreeItemPtr;
typedef void* xmlSchemaParserCtxtPtr;
typedef void* xmlSchemaPtr;
typedef void* xmlSchemaTypePtr;

typedef void* xmlSchemaModelGroupPtr;
typedef void* xmlSchemaParticlePtr;
typedef void* xmlAttrPtr;

// Minimal node with the field used by the vulnerable statement
struct _xmlNode { struct _xmlNode *next; };
typedef struct _xmlNode* xmlNodePtr;

// Vulnerable function — keep signature, minimal locals, and the exact vulnerable line
static xmlSchemaTreeItemPtr
xmlSchemaParseModelGroup(xmlSchemaParserCtxtPtr ctxt, xmlSchemaPtr schema,
                         xmlNodePtr node, xmlSchemaTypeType type,
