/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int main(void) {
    // Prepare pinfo -> points to a comp_unit
    struct comp_unit *unit = calloc(1, sizeof(*unit));
    // Set minimally used fields
    unit->abfd = (struct bfd*)0x1;  // non-NULL; bfd_alloc stub ignores it

    void *pinfo = unit;  // entry expects *pinfo to be comp_unit*

    // Symbols array (not used by neutralized entry); provide NULL-terminated
    asymbol *sym_arr[1] = { NULL };

    // Call entry directly
    _bfd_dwarf2_find_symbol_bias(sym_arr, &pinfo);
    return 0;
}
