#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 128) return 0;
    // Allocate opaque inputs with concrete sizes and make them symbolic
    void *abfd_mem = calloc(1, 64);
    void *link_info_mem = calloc(1, 64);
    { memcpy(abfd_mem, fuzz_data + 0, 64); }
    { memcpy(link_info_mem, fuzz_data + 64, 64); }

    bfd *abfd = (bfd *)abfd_mem;
    struct bfd_link_info *link_info = (struct bfd_link_info *)link_info_mem;

    // Directly invoke the entry point (harness entry pass-through)
    _bfd_elf_compute_section_file_positions(abfd, link_info);
    return 0;
}
