#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdint.h>
#include <stdlib.h>

int entry_func(uint8_t *cp, tmsize_t n); // from harness

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 12) return 0;
    // Allocate a small concrete buffer so that accessing cp[4] goes OOB
    enum { BUF_SZ = 4 }; // only 4 bytes valid, index 0..3
    uint8_t *buf = (uint8_t *)malloc(BUF_SZ);
    if (!buf) return 0;
    { memcpy(buf, fuzz_data + 0, 4); }

    // n controls the branch; make it symbolic but ensure we take n > 8 path
    tmsize_t n;
    { memcpy(&n, fuzz_data + 4, 8); }
    
    // Also keep n within a sane bound to avoid overflow semantics
    

    // Direct call into entry (which directly calls TIFFReverseBits)
    entry_func(buf, n);
    return 0;
}
