/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <stdbool.h>

// Minimal types matching harness/elf-sframe.c
typedef unsigned char bfd_byte;
typedef size_t bfd_size_type;
typedef struct bfd { int dummy; } bfd;
typedef struct asection {
    bfd_size_type size;
    unsigned int flags;
    int sec_info_type;
    struct asection *output_section;
} asection;
struct bfd_link_info { int dummy; };
struct elf_reloc_cookie { int dummy; };

// Prototype of the entry/vulnerable function (4 params)
bool _bfd_elf_parse_sframe(bfd *abfd,
                           struct bfd_link_info *info,
                           asection *sec,
                           struct elf_reloc_cookie *cookie);

int main() {
    bfd *abfd = (bfd*)calloc(1, sizeof(bfd));
    struct bfd_link_info *info = (struct bfd_link_info*)calloc(1, sizeof(struct bfd_link_info));
    asection *sec = (asection*)calloc(1, sizeof(asection));
    struct elf_reloc_cookie *cookie = (struct elf_reloc_cookie*)calloc(1, sizeof(struct elf_reloc_cookie));

    // Concrete initialization to satisfy typical guards (even if neutralized)
    sec->size = 64;           // non-zero concrete size
    sec->flags = 0x1;         // SEC_HAS_CONTENTS
    sec->sec_info_type = 0;   // SEC_INFO_TYPE_NONE
    sec->output_section = NULL; // non-absolute section implied in our harness

    // No symbolicization of sizes/fields to avoid KLEE runtime checks

    (void)_bfd_elf_parse_sframe(abfd, info, sec, cookie);
    return 0;
}
