#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */



typedef unsigned char xmlChar;
typedef int xmlCharEncoding;

typedef struct _xmlSAXHandler xmlSAXHandler;
typedef struct _xmlParserInputBuffer xmlParserInputBuffer;
typedef struct _xmlParserInput xmlParserInput;
typedef struct _xmlParserCtxt xmlParserCtxt;
typedef struct _xmlDtd xmlDtd;

struct _xmlSAXHandler { int _pad; };
struct _xmlParserInputBuffer { int _pad; };
struct _xmlParserInput { int _pad; };
struct _xmlParserCtxt { int _pad; };
struct _xmlDtd { int _pad; };

typedef struct { int properties; } xmlDoc;

xmlDtd *
