#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

int entry_func(struct TIFF *tif); // from harness/tif_dir.c

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 8) return 0;
    // Intentionally undersized allocation to provoke OOB when accessing nested fields
    // Concrete small size per guidelines
    size_t small_sz = 8; // much smaller than struct TIFF
    struct TIFF *tif = (struct TIFF*)calloc(1, small_sz);

    // Optional: make initial bytes symbolic (not required for OOB)
    if (tif) {
        { memcpy(tif, fuzz_data + 0, 8); }
    }

    // Direct call to entry
    entry_func(tif);
    return 0;
}
