/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Declarations from harness
bool _bfd_pex64i_final_link_postscript (bfd * abfd, struct coff_final_link_info *pfinfo);

int main() {
    // Allocate opaque bfd as a byte buffer and cast (bfd is incomplete here)
    bfd *abfd = (bfd *)calloc(1, 1024);

    // These structs have concrete layouts from harness_types.h
    struct coff_final_link_info *pfinfo = (struct coff_final_link_info *)calloc(1, sizeof(struct coff_final_link_info));
    struct bfd_link_info *info = (struct bfd_link_info *)calloc(1, sizeof(struct bfd_link_info));

    // Wire required fields used by the slice
    pfinfo->info = info;
    pfinfo->output_bfd = abfd;  // used by bfd_set_section_contents in the harness slice

    // Direct call to entry (neutralized entry ensures we reach vuln)
    (void)_bfd_pex64i_final_link_postscript(abfd, pfinfo);
    return 0;
}
