/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

/* Prototype from harness */
void png_read_transform_info(png_struct *png_ptr, png_info *info_ptr);

int main(void) {
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info*)calloc(1, sizeof(png_info));
    if (!png_ptr || !info_ptr) return 0;

    /* Make the info object symbolic (so bit_depth can be any value) */
    memset(info_ptr, 0xAA, sizeof(*info_ptr));

    /* UAF/type-confusion pattern: free then use via stale pointer */
    png_info *stale = info_ptr;
    free(info_ptr);

    /* Direct call to the vulnerable function (entry==vuln) */
    png_read_transform_info(png_ptr, stale);
    return 0;
}
