/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

extern int entry_func(double *dp);

int main() {
    // Allocate a too-small buffer (4 bytes). Accessing cp[4] will be OOB.
    char *buf = (char*)malloc(4);
    if (!buf) return 0;
    // Make contents symbolic (not strictly necessary for OOB, but harmless)
    { /* replay: concrete values for "buf_bytes" (4 bytes) */
  static const unsigned char buf_bytes_data[] = {0x00, 0x00, 0x00, 0x00};
  memcpy(buf, buf_bytes_data, (4) < 4 ? (4) : 4);
};

    // Call entry with cast to double* (function casts back to unsigned char*)
    entry_func((double*)buf);
    return 0;
}
