/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>

int main() {
    xmlParserCtxt *ctxt = NULL;      // Trigger NULL deref on ctxt->input
    xmlChar *encoding = NULL;        // Unused in our neutralized body

    xmlSetDeclaredEncoding(ctxt, encoding);
    return 0;
}
