/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef struct png_color_s {
    unsigned char red, green, blue;
} png_color;

typedef struct png_struct_def {
    unsigned int mng_features_permitted;
} png_struct;

typedef struct png_info_def {
    int color_type;
    int bit_depth;
} png_info;

extern void png_set_PLTE(png_struct *png_ptr, png_info *info_ptr,
                         const png_color *palette, int num_palette);

#ifndef PNG_COLOR_TYPE_PALETTE
#define PNG_COLOR_TYPE_PALETTE 3
#endif

int main() {
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info *info_ptr = (png_info*)calloc(1, sizeof(png_info));
    if (!png_ptr || !info_ptr) return 0;

    // Initialize with concrete values
    info_ptr->color_type = PNG_COLOR_TYPE_PALETTE;
    info_ptr->bit_depth = 8;

    png_color *palette = (png_color*)calloc(256, sizeof(png_color));
    if (!palette) return 0;
    int num_palette = 256;

    // Free info_ptr to create a stale pointer (UAF) before calling vulnerable function
    free(info_ptr);

    // Call entry/vulnerable function; dereference of freed info_ptr should be flagged by KLEE
    png_set_PLTE(png_ptr, (png_info*)info_ptr, (const png_color*)palette, num_palette);

    return 0;
}
