#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>

#ifndef ATTRIBUTE_UNUSED
#define ATTRIBUTE_UNUSED
#endif

// Prototype from harness
extern void _bfd_dwarf1_cleanup_debug_info (bfd *abfd ATTRIBUTE_UNUSED, void **pinfo);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 128) return 0;
    // Allocate and initialize the stash to satisfy early guards
    struct dwarf1_debug *stash = (struct dwarf1_debug *)calloc(1, sizeof(struct dwarf1_debug));

    // Allocate concrete buffers so free() succeeds
    size_t sz = 64;
    stash->debug_section = (bfd_byte *)malloc(sz);
    stash->line_section  = (bfd_byte *)malloc(sz);

    // Make contents symbolic (not strictly necessary, but good practice)
    { memcpy(stash->debug_section, fuzz_data + 0, 64); }
    { memcpy(stash->line_section, fuzz_data + 64, 64); }

    // Prepare pinfo as void** as expected by the API
    void *pinfo = (void *)stash;

    // Call entry (also the vulnerable function)
    _bfd_dwarf1_cleanup_debug_info(NULL, &pinfo);
    return 0;
}
