/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int htmlCtxtSetOptions(htmlParserCtxt *ctxt, int options);

int main() {
    // Allocate a concrete parser context; calloc ensures sax == NULL to trigger NULL deref
    htmlParserCtxt *ctxt = (htmlParserCtxt *)calloc(1, sizeof(*ctxt));

    // Make options symbolic but require HTML_PARSE_NOBLANKS to be set to enter the vulnerable branch
    int options = 0;
    { /* replay: concrete values for "options" (4 bytes) */
  static const unsigned char options_data[] = {0x40, 0x40, 0x40, 0x40};
  memcpy(&options, options_data, (sizeof(options)) < 4 ? (sizeof(options)) : 4);
};

    // Optionally allow HUGE to be either set or not; dict is NULL so xmlDictSetLimit won't be called

    // Direct call to entry function
    htmlCtxtSetOptions(ctxt, options);
    return 0;
}
