#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdint.h>
#include <stdlib.h>

// entry from harness
int harness_entry(double *dp, tmsize_t n);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    // Allocate an undersized buffer (< 8 bytes) so cp[7] is OOB
    size_t small = 4;  // concrete size as required
    unsigned char *raw = (unsigned char *)malloc(small);
    { memcpy(raw, fuzz_data + 0, 4); }

    double *dp = (double *)raw;  // intentionally mis-sized
    tmsize_t n = 1;               // ensure loop runs once

    // Call entry (direct pass-through to vulnerable function)
    harness_entry(dp, n);
    return 0;
}
