/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

extern int UTF16BEToUTF8(void *vctxt,
                         unsigned char *out, int *outlen,
                         const unsigned char *in, int *inlen,
                         int flush);

int main() {
    // Intentionally small input buffer (1 byte) while claiming inlen=2 to trigger in[1] OOB
    unsigned char *in = (unsigned char *)malloc(1);
    if (!in) return 0;
    { /* replay: concrete values for "in_bytes" (1 bytes) */
  static const unsigned char in_bytes_data[] = {0x00};
  memcpy(in, in_bytes_data, (1) < 1 ? (1) : 1);
};

    // Output buffer: small but concrete
    unsigned char outbuf[16];
    { /* replay: concrete values for "out_bytes" (16 bytes) */
  static const unsigned char out_bytes_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(outbuf, out_bytes_data, (sizeof(outbuf)) < 16 ? (sizeof(outbuf)) : 16);
};

    int inlen = 2;   // Even length makes inend = in + 2 and enters loop once
    int outlen = 16; // Enough space for single-byte/2-byte encodings

    (void)UTF16BEToUTF8(NULL, outbuf, &outlen, in, &inlen, 0);
    return 0;
}
