#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 24) return 0;
    // Allocate input and output BFDs
    bfd *ibfd = (bfd *)calloc(1, sizeof(bfd));
    bfd *obfd = (bfd *)calloc(1, sizeof(bfd));

    // Allocate and attach tdata for ibfd (required by elf_tdata in harness)
    elf_obj_tdata *itd = (elf_obj_tdata *)calloc(1, sizeof(elf_obj_tdata));
    ibfd->tdata = itd;

    // Minimal phdr array with 1 entry
    Elf_Internal_Phdr *ph = (Elf_Internal_Phdr *)malloc(sizeof(Elf_Internal_Phdr) * 1);
    memset(ph, 0, sizeof(Elf_Internal_Phdr) * 1);
    itd->phdr = ph;

    // Set number of segments to 1
    itd->elf_header.e_phnum = 1;

    // Make the single program header fields symbolic so KLEE explores both branches
    { memcpy(&ph[0], fuzz_data + 0, 24); }

    // Call entry function (neutralized to direct pass-through in harness)
    _bfd_elf_copy_private_header_data(ibfd, obfd);
    return 0;
}
