/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate parser context and input
    xmlParserCtxt *ctxt = (xmlParserCtxt *)calloc(1, sizeof(*ctxt));
    xmlParserInput *in = (xmlParserInput *)calloc(1, sizeof(*in));

    // Single-byte buffer to trigger OOB when last byte is '&'
    xmlChar *buf = (xmlChar *)malloc(1);
    { /* replay: concrete values for "entity_buf" (1 bytes) */
  static const unsigned char entity_buf_data[] = {0x26};
  memcpy(buf, entity_buf_data, (1) < 1 ? (1) : 1);
};
    // Constrain to '&' so condition (c == '&') holds and str[1] is evaluated
    /* klee_assume removed for replay */

    // Wire pointers
    in->base = buf;
    in->cur = buf;
    in->end = buf + 1; // length = 1

    // Fill context
    ctxt->options = 0;   // not XML_PARSE_HUGE
    ctxt->input = in;
    ctxt->inputNr = 0;
    ctxt->instate = 0;

    // Call entry (pass-through to vulnerable function in harness)
    xmlParseEntityValue(ctxt, NULL);

    return 0;
}
