/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate BFD container
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));

    // Allocate the hash table object that obfd->link.hash will point to
    struct elf_x86_link_hash_table *htab = (struct elf_x86_link_hash_table *)calloc(1, sizeof(struct elf_x86_link_hash_table));

    // Ensure the vulnerable branch is taken by making loc_hash_memory non-NULL
    void *mem = malloc(64);
    memset(mem, 0xAA, 64);
    htab->loc_hash_memory = mem;

    // Install pointer then free it to create a stale pointer (UAF scenario)
    abfd->link.hash = htab;
    free(htab);

    // Call entry (neutralized) which directly invokes the vulnerable function
    _bfd_x86_elf_link_hash_table_create(abfd);
    return 0;
}
