/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

char *elfcore_write_linux_prpsinfo32(bfd *abfd, char *buf, int *bufsiz, const struct elf_internal_linux_prpsinfo *prpsinfo);

int main() {
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    struct elf_backend_data *bed = (struct elf_backend_data *)calloc(1, sizeof(struct elf_backend_data));

    { /* replay: concrete values for "linux_prpsinfo32_ugid16" (4 bytes) */
    static const unsigned char linux_prpsinfo32_ugid16_data[] = {0x01, 0x00, 0x00, 0x00};
    memcpy(&bed->linux_prpsinfo32_ugid16, linux_prpsinfo32_ugid16_data, (sizeof(bed->linux_prpsinfo32_ugid16)) < 4 ? (sizeof(bed->linux_prpsinfo32_ugid16)) : 4);
  };
    /* assume removed */

    abfd->xvec = bed;

    int bufsiz = 256;
    char *buf = (char *)malloc((size_t)bufsiz);
    memset(buf, 0, (size_t)bufsiz);

    struct elf_internal_linux_prpsinfo *prps = (struct elf_internal_linux_prpsinfo *)calloc(1, sizeof(struct elf_internal_linux_prpsinfo));

    /* Free backend to create a stale abfd->xvec before dereference inside target */
    free(bed);

    (void)elfcore_write_linux_prpsinfo32(abfd, buf, &bufsiz, prps);
    return 0;
}
