#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 8) return 0;
    // Allocate the target struct concretely
    struct elf_strtab_hash *tab = (struct elf_strtab_hash *)malloc(sizeof(struct elf_strtab_hash));
    if (!tab) return 0;

    // Initialize fields symbolically (size is read in the vulnerable statement)
    { memcpy(&tab->size, fuzz_data + 0, 8); }

    // Create a UAF scenario: free the object, then pass stale pointer
    free(tab);

    // Call entry/vulnerable function directly (pass-through)
    _bfd_elf_strtab_finalize(tab);

    return 0;
}
