/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdint.h>
/* Minimal typedefs to match harness/pngset.c */
typedef uint32_t png_uint_32;
typedef unsigned char png_byte;
typedef struct png_struct_def { int dummy; } png_struct;
typedef struct png_info_def {
    png_uint_32 x_pixels_per_unit;
    png_uint_32 y_pixels_per_unit;
    png_byte    phys_unit_type;
    png_uint_32 valid;
} png_info;

/* Prototype to match harness definition */
void png_set_pHYs(const png_struct *png_ptr, png_info *info_ptr,
                  png_uint_32 res_x, png_uint_32 res_y, int unit_type);

int main() {
    // Allocate png_struct (must be non-NULL)
    png_struct *png_ptr = (png_struct *)malloc(sizeof(png_struct));
    if (!png_ptr) return 0;
    memset(png_ptr, 0xAA, sizeof(*png_ptr));

    // Allocate png_info, then free it to create a stale pointer (UAF scenario)
    png_info *info_ptr = (png_info *)malloc(sizeof(png_info));
    if (!info_ptr) return 0;
    memset(info_ptr, 0xAA, sizeof(*info_ptr));

    free(info_ptr);

    // Symbolic parameters
    png_uint_32 res_x, res_y; int unit_type;
    memset(&res_x, 0xAA, sizeof(res_x));
    memset(&res_y, 0xAA, sizeof(res_y));
    memset(&unit_type, 0xAA, sizeof(unit_type));

    // Direct call to entry/vulnerable function
    png_set_pHYs(png_ptr, info_ptr, res_x, res_y, unit_type);
    return 0;
}
