#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdint.h>

/* Minimal replicas matching harness/elflink.c */
typedef struct bfd {
    struct { void *hash; } link;
} bfd;

struct dynamic_dummy { void *contents; };

struct elf_link_hash_table {
    void *dynstr;
    void *merge_info;
    struct dynamic_dummy *dynamic;
    void *first_hash;
};

void _bfd_elf_link_hash_table_free(bfd *obfd);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 64) return 0;
    bfd *obfd = (bfd *)calloc(1, sizeof(bfd));
    struct elf_link_hash_table *htab = (struct elf_link_hash_table *)calloc(1, sizeof(struct elf_link_hash_table));

    obfd->link.hash = htab;

    /* Allocate a concrete dynstr buffer and make contents symbolic. */
    size_t dynsz = 64;
    unsigned char *dyn = (unsigned char *)malloc(dynsz);
    { memcpy(dyn, fuzz_data + 0, 64); }

    /* Set fields to drive the target path. */
    htab->dynstr = (void *)dyn;     /* non-NULL so _bfd_elf_strtab_free is called */
    htab->merge_info = NULL;        /* avoid unrelated frees */
    htab->dynamic = NULL;           /* avoid dynamic->contents free */
    htab->first_hash = NULL;        /* avoid extra frees */

    /* Call entry == vulnerable function; harness will deref htab->dynstr post-free (UAF). */
    _bfd_elf_link_hash_table_free(obfd);
    return 0;
}
