#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */



// Minimal local typedefs to match signatures
typedef unsigned char xmlChar;

typedef struct _xmlNode { void *dummy; } *xmlNodePtr;
typedef struct _xmlSchema { int dummy; } *xmlSchemaPtr;

typedef void* xmlSchemaTreeItemPtr; // generic tree item pointer

typedef int xmlSchemaTypeType;
typedef int xmlParserErrors;

typedef struct _xmlSchemaType { int dummy; } *xmlSchemaTypePtr;

typedef struct _xmlSchemaRedef {
    void *reference; // field used at the vulnerable site
    // other fields are irrelevant for the sliced harness
} xmlSchemaRedef;

typedef struct _xmlSchemaParserCtxt {
    xmlSchemaRedef *redef;   // dereferenced at the vulnerable line
    int redefCounter;        // incremented after the assignment
} *xmlSchemaParserCtxtPtr;

typedef void* xmlSchemaAbstractCtxtPtr; // entry signature requires this

// In real code, this macro is a cast prefix. Define it so that
//  "WXS_BASIC_CAST part" expands to "(void*) part" and compiles.
#ifndef WXS_BASIC_CAST
#define WXS_BASIC_CAST (void*)
#endif

// Forward decl with exact signature from source excerpt
static xmlSchemaTreeItemPtr xmlSchemaParseModelGroup(xmlSchemaParserCtxtPtr ctxt,
                                                    xmlSchemaPtr schema,
                                                    xmlNodePtr node,
                                                    xmlSchemaTypeType type,
                                                    int withParticle);

// ENTRY FUNCTION: MUST be pure pass-through (no guards/logic)
void xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                             xmlParserErrors error,
                             xmlNodePtr node,
                             xmlSchemaTypePtr type /* ATTRIBUTE_UNUSED */,
                             const char *message,
                             int nbval,
                             int nbneg,
                             xmlChar **values)
{
    // Direct call to the vulnerable function, no checks/guards
    xmlSchemaParserCtxtPtr ctxt = (xmlSchemaParserCtxtPtr) actxt;
    xmlSchemaPtr schema = (xmlSchemaPtr) actxt; // placeholder
    (void)error; (void)type; (void)message; (void)nbval; (void)nbneg; (void)values;
    (void) xmlSchemaParseModelGroup(ctxt, schema, node, 0, 0);
}

// VULNERABLE FUNCTION: emulate UAF by freeing ctxt->redef before its use
static xmlSchemaTreeItemPtr
xmlSchemaParseModelGroup(xmlSchemaParserCtxtPtr ctxt, xmlSchemaPtr schema,
                         xmlNodePtr node, xmlSchemaTypeType type,
