/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdint.h>

// Minimal replicas matching harness/xmlschemas.c
typedef unsigned char xmlChar;

typedef struct _xmlNode { void *dummy; } *xmlNodePtr;
typedef struct _xmlSchema { int dummy; } *xmlSchemaPtr;

typedef void* xmlSchemaTreeItemPtr; // generic tree item pointer

typedef int xmlSchemaTypeType;
typedef int xmlParserErrors;

typedef struct _xmlSchemaType { int dummy; } *xmlSchemaTypePtr;

typedef struct _xmlSchemaRedef {
    void *reference;
} xmlSchemaRedef;

typedef struct _xmlSchemaParserCtxt {
    xmlSchemaRedef *redef;
    int redefCounter;
} *xmlSchemaParserCtxtPtr;

typedef void* xmlSchemaAbstractCtxtPtr;

// Prototype of entry function defined in harness/xmlschemas.c
void xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                             xmlParserErrors error,
                             xmlNodePtr node,
                             xmlSchemaTypePtr type,
                             const char *message,
                             int nbval,
                             int nbneg,
                             xmlChar **values);

int main() {
    // Allocate parser context and required substructures
    xmlSchemaParserCtxtPtr ctxt = (xmlSchemaParserCtxtPtr)calloc(1, sizeof(*ctxt));
    if (!ctxt) return 0;

    ctxt->redef = (xmlSchemaRedef*)calloc(1, sizeof(*ctxt->redef));
    if (!ctxt->redef) return 0;

    // Minimal node allocation
    xmlNodePtr node = (xmlNodePtr)calloc(1, sizeof(*node));

    // Call entry; other parameters are unused in our neutralized slice
    xmlSchemaAbstractCtxtPtr actxt = (xmlSchemaAbstractCtxtPtr)ctxt;
    xmlSchemaComplexTypeErr(actxt, 0, node, NULL, NULL, 0, 0, NULL);

    return 0;
}
