/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate concrete structs (no symbolic sizes)
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info*)calloc(1, sizeof(png_info));

    // Initialize fields that are used in the vulnerable path
    if (!png_ptr || !info_ptr) return 0;

    // Make the contents symbolic to overapproximate, but use concrete allocation
    memset(info_ptr, 0xAA, sizeof(*info_ptr));
    memset(png_ptr, 0xAA, sizeof(*png_ptr));

    // Encourage taking the branch (not strictly necessary for UAF read)
    // But set a sane default if unconstrained
    info_ptr->valid |= PNG_INFO_acTL;

    // Create the UAF: free the info struct while keeping the stale pointer
    free(info_ptr);

    // Call entry (pass-through) which will read info_ptr->valid in before_PLTE
    png_write_info(png_ptr, info_ptr);

    return 0;
}
