#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Prototypes from the harness
bool _bfd_elf_compute_section_file_positions(bfd *abfd, struct bfd_link_info *link_info);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 516) return 0;
    // Allocate an opaque bfd object: use a concrete blob and cast
    // since bfd may be incomplete in harness_types.h
    void *abfd_mem = malloc(512);
    
    { memcpy(abfd_mem, fuzz_data + 0, 512); }
    bfd *abfd = (bfd *)abfd_mem;

    // Allocate link_info concretely; make fields symbolic if any
    struct bfd_link_info *link_info = malloc(sizeof(*link_info));
    
    { memcpy(link_info, fuzz_data + 512, 4); }

    // Directly call the entry; harness strips all guards and forwards to vuln
    (void)_bfd_elf_compute_section_file_positions(abfd, link_info);
    return 0;
}
