/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

/* Entry is the same as vulnerable function: png_get_pixel_aspect_ratio_fixed */
extern png_fixed_point png_get_pixel_aspect_ratio_fixed(const png_struct *png_ptr,
                                                       const png_info *info_ptr);

int main() {
    /* Allocate concrete objects */
    png_struct *png_ptr = (png_struct *)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info *)calloc(1, sizeof(png_info));

    /* Make the WHOLE struct symbolic (avoid per-field size issues) */
    memset(info_ptr, 0xAA, sizeof(*info_ptr));

    /* Constrain to pass guards */
    /* klee_assume removed */
    /* klee_assume removed */
    /* klee_assume removed */
    /* klee_assume removed */
    /* klee_assume removed */

    /* Optional UAF-style branch to explore stale pointer behavior */
    int do_uaf = 0;
    memset(&do_uaf, 0xAA, sizeof(do_uaf));
    if (do_uaf) {
        free(info_ptr);
        /* Intentionally leave info_ptr non-NULL to simulate stale pointer */
    }

    (void)png_get_pixel_aspect_ratio_fixed(png_ptr, info_ptr);
    return 0;
}
