/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

// Opaque forward declarations matching harness function signature
typedef struct bfd bfd;
struct coff_final_link_info;

// Entry function prototype from harness
extern bool _bfd_pei_final_link_postscript(bfd *abfd, struct coff_final_link_info *pfinfo);

int main() {
    // Concrete allocations (sizes arbitrary but concrete; callee does not dereference)
    bfd *abfd = (bfd*)calloc(1, 16);
    struct coff_final_link_info *pfinfo = (struct coff_final_link_info*)calloc(1, 32);

    (void)_bfd_pei_final_link_postscript(abfd, pfinfo);
    return 0;
}
