/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stddef.h>
#include <stdint.h>

#ifndef SYMNMLEN
#define SYMNMLEN 8
#endif

typedef struct bfd bfd;

struct internal_syment {
  union {
    char _n_name[SYMNMLEN];
    struct {
      uint32_t _n_zeroes;
      uint32_t _n_offset;
    } _n_n;
  } _n;
};

extern const char * _bfd_coff_internal_syment_name (bfd *abfd, const struct internal_syment *sym, char *buf);

int main(void) {
    struct internal_syment sym_local;
    // Zero-init
    for (size_t i = 0; i < sizeof(sym_local); ++i)
        ((unsigned char*)&sym_local)[i] = 0;

    // Take the early branch so memcpy(buf, ..., SYMNMLEN) then buf[SYMNMLEN]='\0' executes
    sym_local._n._n_n._n_offset = 0; // condition (_n_zeroes != 0 || _n_offset == 0)

    // Intentionally undersized buffer to trigger write to buf[SYMNMLEN]
    char buf[SYMNMLEN];
    memset(buf, 0, sizeof(buf));

    const char *ret = _bfd_coff_internal_syment_name((bfd*)0, &sym_local, buf);
    (void)ret;
    return 0;
}
