#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Prototype from harness */
bool bfd_cache_close(bfd *abfd);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 16) return 0;
    // Allocate concrete bfd object
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));

    // Make iovec pointer symbolic so the compare reads the field
    const struct bfd_iovec *sym_iovec;
    { memcpy(&sym_iovec, fuzz_data + 0, 8); }
    abfd->iovec = sym_iovec;

    // Optional: give iostream a non-NULL allocation (not required here)
    void *io = malloc(8);
    { memcpy(io, fuzz_data + 8, 8); }
    abfd->iostream = io;

    // WMI-2/UAF pattern: free the bfd object, then use it in bfd_cache_close
    free(abfd);

    // Use-after-free: dereference of abfd->iovec in _bfd_cache_close_unlocked
    (void)bfd_cache_close(abfd);

    return 0;
}
