/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Minimal mirrored typedefs matching harness/syms.c */
typedef unsigned long bfd_vma;
typedef size_t bfd_size_type;
typedef unsigned char bfd_byte;
typedef struct bfd { int _d; } bfd;
typedef struct asymbol { int _d; } asymbol;
typedef struct asection { int _d; } asection;

struct indexentry {
  bfd_vma val;
  bfd_byte *stab;
  bfd_byte *str;
  char *directory_name;
  char *file_name;
  char *function_name;
  int idx;
};

struct stab_find_info {
  asection *stabsec;
  asection *strsec;
  bfd_byte *stabs;
  bfd_byte *strs;
  struct indexentry *indextable;
  int indextablesize;
  char *filename;
};

/* Declaration from harness/syms.c */
bool _bfd_stab_section_find_nearest_line(
    bfd *abfd,
    asymbol **symbols,
    asection *section,
    bfd_vma offset,
    bool *pfound,
    const char **pfilename,
    const char **pfnname,
    unsigned int *pline,
    void **pinfo);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 96) return 0;
    // Allocate minimal objects required by the entry function
    bfd *abfd = (bfd*)calloc(1, sizeof(bfd));
    asection *stabsec = (asection*)calloc(1, sizeof(asection));
    asection *strsec  = (asection*)calloc(1, sizeof(asection));

    struct stab_find_info *info = (struct stab_find_info*)calloc(1, sizeof(struct stab_find_info));
    // Satisfy early guards: non-NULL sections and allocated buffers
    info->stabsec = stabsec;
    info->strsec  = strsec;

    const size_t STABS_SZ = 64;
    const size_t STRS_SZ  = 32;
    info->stabs = (bfd_byte*)malloc(STABS_SZ);
    info->strs  = (bfd_byte*)malloc(STRS_SZ);
    if (!info->stabs || !info->strs) return 0;
    { memcpy(info->stabs, fuzz_data + 0, 64); }
    { memcpy(info->strs, fuzz_data + 64, 32); }

    // Prepare parameters
    asymbol **symbols = NULL;
    asection *section = NULL;
    bfd_vma offset = 0;
    bool found = false;
    const char *filename = NULL;
    const char *fnname = NULL;
    unsigned int line = 0;

    // pinfo is an in/out pointer to the info cache
    void *pinfo = (void*)info;

    // Direct call to entry/vulnerable function
    _bfd_stab_section_find_nearest_line(
        abfd, symbols, section, offset,
        &found, &filename, &fnname, &line, &pinfo);

    return 0;
}
