#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 192) return 0;
    // Allocate the bfd object
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));

    // Allocate buffers for strings and external symbols so free() operates on valid memory
    char *strs = (char *)malloc(128);
    char *extsyms = (char *)malloc(64);

    // Make contents symbolic (not strictly necessary for this path)
    if (strs) { memcpy(strs, fuzz_data + 0, 128); }
    if (extsyms) { memcpy(extsyms, fuzz_data + 128, 64); }

    // Set fields so that _bfd_coff_free_symbols will take the free paths
    abfd->strings = strs;           // non-NULL triggers the vulnerable free()
    abfd->external_syms = extsyms;  // non-NULL also triggers external_syms free first
    abfd->strings_len = 128;
    abfd->flags = 0;
    abfd->symcount = 0;
    abfd->start_address = 0;
    abfd->is_linker_input = 0;

    // Dummy parameters for the entry function; they are unused in the neutralized harness
    unsigned nscns = 0;
    struct internal_filehdr fih = {0};
    struct internal_aouthdr iah = {0};

    // Call the entry function which directly invokes the vulnerable function
    coff_real_object_p(abfd, nscns, &fih, &iah);

    return 0;
}
