/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

int main() {
    // Allocate parser context and input
    xmlParserCtxt *ctxt = (xmlParserCtxt *)calloc(1, sizeof(*ctxt));
    xmlParserInput *in = (xmlParserInput *)calloc(1, sizeof(*in));
    if (!ctxt || !in) return 0;
    ctxt->input = in;

    // Concrete buffer size (no symbolic sizes)
    const size_t buf_sz = 64;
    xmlChar *buf = (xmlChar *)malloc(buf_sz);
    if (!buf) return 0;

    // Make buffer contents symbolic so KLEE can drive branches
    { /* replay: concrete values for "xml_buf" (64 bytes) */
  static const unsigned char xml_buf_data[] = {0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c};
  memcpy(buf, xml_buf_data, (buf_sz) < 64 ? (buf_sz) : 64);
};

    // Set base/cur/end such that cur < end but cur[1] is out-of-bounds
    in->base = buf;
    in->cur  = buf + buf_sz - 1;   // last valid byte
    in->end  = buf + buf_sz;       // one past last valid byte

    // Ensure we take the '<' branch so cur[1] is evaluated and causes OOB
    /* klee_assume removed for replay */

    // Call entry (neutralized pass-through)
    xmlParseChunk(ctxt, NULL, 0, 0);
    return 0;
}
