/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate concrete png_struct and png_info
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info *info = (png_info*)malloc(sizeof(png_info));
    if (!png_ptr || !info) return 0;

    // Optionally make png_ptr symbolic (not required for the bug)
    memset(png_ptr, 0xAA, sizeof(*png_ptr));

    // Initialize info with symbolic data, then FREE it to create a UAF scenario
    memset(info, 0xAA, sizeof(*info));
    // Ensure PNG_FREE_TRNS bit may or may not be set (KLEE explores both)
    // No need to force it; the read happens regardless.

    // Free the info object but keep the stale pointer value
    free(info);

    // Prepare pointer-to-pointer as required by entry signature
    png_info *stale = info;            // stale pointer into freed memory
    png_info **info_ptr_ptr = &stale;  // entry will pass this into png_free_data

    // Call entry function (neutralized to direct call of png_free_data)
    png_destroy_info_struct(png_ptr, info_ptr_ptr);

    return 0;
}
