/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

#include <stdbool.h>

// Entry prototype
bool _bfd_write_archive_contents(bfd *arch);

int main() {
    // Opaque allocation for 'bfd' 
    void *mem = calloc(1, 1024);
    if (!mem) return 0;
    bfd *arch = (bfd*)mem;

    // Directly call the entry; it's a pass-through in the harness
    _bfd_write_archive_contents(arch);
    return 0;
}
