#include <stdint.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stddef.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 8) return 0;
    size_t size = 0;
    { memcpy(&size, fuzz_data + 0, 8); }
    // Force size to exceed the largest prime in our minimal prime_tab (7)

    (void)htab_create_alloc_ex(size, (htab_hash)0, (htab_eq)0, (htab_del)0,
                               (void*)0, (htab_alloc_with_arg)0, (htab_free_with_arg)0);
    return 0;
}
