/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Opaque forward decls matching harness signatures
typedef struct _xmlMutex xmlMutex;
void xmlFreeMutex(xmlMutex *tok);

int main() {
    // Allocate a concrete-sized buffer to serve as xmlMutex storage
    const size_t sz = 64; // concrete size, >= sizeof(xmlMutex) in harness
    xmlMutex *tok = (xmlMutex*)malloc(sz);
    if (!tok) return 0;

    // Make the contents symbolic (not the pointer itself)
    { /* replay: concrete values for "tok_mem" (64 bytes) */
  static const unsigned char tok_mem_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(tok, tok_mem_data, (sz) < 64 ? (sz) : 64);
};

    // Free first to create a stale pointer; xmlCleanupMutex will then deref
    free(tok);

    // Call entry; it will pass through to xmlCleanupMutex and dereference
    xmlFreeMutex(tok);
    return 0;
}
