#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* harness/spine.c - minimal sliced harness */

/* Minimal type universe for this slice */
typedef unsigned char xmlChar;

typedef enum { XML_SCHEMA_TYPE_GROUP = 1 } xmlSchemaTypeType;

typedef struct _xmlSchemaBasicItem {
    xmlSchemaTypeType type;
} xmlSchemaBasicItem, *xmlSchemaBasicItemPtr;

typedef struct _xmlSchemaRedef {
    xmlSchemaBasicItemPtr item;
    const xmlChar *refName;
    const xmlChar *refTargetNs;
} xmlSchemaRedef, *xmlSchemaRedefPtr;

typedef struct _xmlSchemaTreeItem {
    struct _xmlSchemaTreeItem *children;
} xmlSchemaTreeItem, *xmlSchemaTreeItemPtr;

typedef struct _xmlSchemaParserCtxt {
    int isRedefine;
    xmlSchemaRedefPtr redef;
    int redefCounter;
} xmlSchemaParserCtxt, *xmlSchemaParserCtxtPtr;

/* Opaque placeholders for parameters we don't dereference */
typedef struct _xmlSchema *xmlSchemaPtr;
typedef struct _xmlNode *xmlNodePtr;
typedef struct _xmlAttr *xmlAttrPtr;
typedef struct _xmlSchemaType *xmlSchemaTypePtr;
typedef void* xmlSchemaAbstractCtxtPtr;
typedef int xmlParserErrors;
typedef struct _xmlSchemaModelGroup *xmlSchemaModelGroupPtr;
typedef struct _xmlSchemaParticle *xmlSchemaParticlePtr;

/* Vulnerable function (neutralized) */
static xmlSchemaTreeItemPtr
xmlSchemaParseModelGroup(xmlSchemaParserCtxtPtr ctxt, xmlSchemaPtr schema,
                         xmlNodePtr node, xmlSchemaTypeType type,
