/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <string.h>

/* Minimal mirrored types to match harness/spine.c */
typedef unsigned char xmlChar;

typedef enum { XML_SCHEMA_TYPE_GROUP = 1 } xmlSchemaTypeType;

typedef struct _xmlSchemaBasicItem {
    xmlSchemaTypeType type;
} xmlSchemaBasicItem, *xmlSchemaBasicItemPtr;

typedef struct _xmlSchemaRedef {
    xmlSchemaBasicItemPtr item;
    const xmlChar *refName;
    const xmlChar *refTargetNs;
} xmlSchemaRedef, *xmlSchemaRedefPtr;

typedef struct _xmlSchemaParserCtxt {
    int isRedefine;
    xmlSchemaRedefPtr redef;
    int redefCounter;
} xmlSchemaParserCtxt, *xmlSchemaParserCtxtPtr;

/* Opaque placeholders matching harness */
typedef void* xmlSchemaAbstractCtxtPtr;
typedef int xmlParserErrors;
typedef struct _xmlNode *xmlNodePtr;
typedef struct _xmlSchemaType *xmlSchemaTypePtr;

/* Entry function prototype from harness */
void xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                             xmlParserErrors error,
                             xmlNodePtr node,
                             xmlSchemaTypePtr type,
                             const char *message,
                             int nbval,
                             int nbneg,
                             xmlChar **values);

int main() {
    // Build parser context with a stale pointer in redef->item
    xmlSchemaParserCtxt *ctxt = (xmlSchemaParserCtxt*)calloc(1, sizeof(*ctxt));
    xmlSchemaRedef *redef = (xmlSchemaRedef*)calloc(1, sizeof(*redef));
    xmlSchemaBasicItem *item = (xmlSchemaBasicItem*)calloc(1, sizeof(*item));

    ctxt->isRedefine = 1;
    ctxt->redef = redef;
    ctxt->redefCounter = 0;

    item->type = XML_SCHEMA_TYPE_GROUP;
    ctxt->redef->item = item;  // store pointer

    // Free the item to set up UAF before call
    free(item);

    xmlSchemaComplexTypeErr((xmlSchemaAbstractCtxtPtr)ctxt,
                            0,
                            (xmlNodePtr)0,
                            (xmlSchemaTypePtr)0,
                            (const char*)0,
                            0, 0,
                            (xmlChar**)0);
    return 0;
}
