/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

int main() {
    // Allocate concrete instances of the harness-defined types
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    png_info  *info_ptr = (png_info*)calloc(1, sizeof(*info_ptr));

    // Ensure allocations succeeded
    if (!png_ptr || !info_ptr) return 0;

    // Make the key guard field symbolic and ensure loop executes at least once
    memset(&info_ptr->num_text, 0xAA, sizeof(info_ptr->num_text));
    /* klee_assume removed */
    /* klee_assume removed */

    // Unused in our neutralized harness but keep symbolic for generality
    int transforms; void *params = NULL;
    memset(&transforms, 0xAA, sizeof(transforms));

    // Direct call into entry (no guards in harness version)
    png_write_png(png_ptr, info_ptr, transforms, params);

    return 0;
}
