#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdint.h>
#include <stdlib.h>

int harness_entry(uint16_t *wp);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 1) return 0;
    unsigned char *buf = (unsigned char *)malloc(1);
    if (!buf) return 0;
    { memcpy(buf, fuzz_data + 0, 1); }
    uint16_t *wp = (uint16_t *)buf;
    harness_entry(wp);
    return 0;
}
