/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

int main() {
    // Allocate concrete png_struct and png_info
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info *info_ptr = (png_info*)calloc(1, sizeof(png_info));
    if (!png_ptr || !info_ptr) return 0;

    // Prepare minimal plausible state prior to free
    // Set unknown_chunks_num non-zero so that if the dereference didn't crash,
    // the branch would be taken; set before free to avoid UAF writes.
    unsigned int ucn;
    memset(&ucn, 0xAA, sizeof(ucn));
    /* klee_assume removed */
    info_ptr->unknown_chunks_num = ucn;

    // Free info_ptr to create a stale pointer; subsequent dereference in
    // write_unknown_chunks should trigger .free.err in KLEE.
    free(info_ptr);

    // Call entry (pass-through) with the stale pointer value
    png_write_info_before_PLTE(png_ptr, (const png_info*)info_ptr);

    return 0;
}
