/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>

int main() {
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    if (!abfd) return 0;
    struct bfd_link_info *link_info = NULL;

    abfd->output_has_begun = 0;
    abfd->flags = 0;

    _bfd_elf_compute_section_file_positions(abfd, link_info);
    return 0;
}
