/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stddef.h>
#include <stdlib.h>

int main() {
    // Allocate a concrete png_struct object
    png_struct *png = (png_struct*)calloc(1, sizeof(png_struct));

    // Keep num_pal small and concrete to execute loop body once
    png_uint_32 num_pal = 1;

    // Intentionally pass a NULL (or invalid) palette to trigger OOB/invalid read on pal_ptr->red
    const png_color *palette = (const png_color*)0;

    // Direct call to vulnerable entry (no guards here)
    png_write_PLTE(png, palette, num_pal);
    return 0;
}
