/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>

#ifndef READ_PORT
#define READ_PORT 0
#endif
#ifndef WRITE_PORT
#define WRITE_PORT 1
#endif

/* Mirror minimal layout from harness/pex-common.c */
struct pex_funcs { int dummy; };
struct pex_obj {
    int next_input;
    const struct pex_funcs *funcs;
};

/* Entry prototype */
extern const char * pex_run(struct pex_obj *obj, int flags, const char *executable,
                            char * const * argv, const char *orig_outname,
                            const char *errname, int *err);

int main() {
    struct pex_obj *obj = (struct pex_obj *)calloc(1, sizeof(struct pex_obj));

    int flags; { /* replay: concrete values for "flags" (4 bytes) */
    static const unsigned char flags_data[] = {0x00, 0x00, 0x00, 0x00};
    memcpy(&flags, flags_data, (sizeof(flags)) < 4 ? (sizeof(flags)) : 4);
  };

    const char *executable = NULL;
    char * const *argv = NULL;
    const char *orig_outname = NULL;
    const char *errname = NULL;
    int err = 0;

    pex_run(obj, flags, executable, argv, orig_outname, errname, &err);
    return 0;
}
