/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdint.h>
#include <stdlib.h>
typedef int32_t png_int_32;
typedef unsigned char png_byte;

typedef struct png_struct_def { int dummy; } png_struct;
typedef struct png_info_def { unsigned long free_me; } png_info;

/* Forward declaration of the target function implemented in harness/pngset.c */
extern void png_set_pCAL(const png_struct *png_ptr, png_info *info_ptr,
    const char *purpose, png_int_32 X0, png_int_32 X1, int type,
    int nparams, const char *units, char **params);

int main() {
    png_struct *png = (png_struct*)calloc(1, sizeof(png_struct));
    png_info *info = (png_info*)calloc(1, sizeof(png_info));

    if (png) {
        memset(&png->dummy, 0xAA, sizeof(png->dummy));
    }
    if (info) {
        memset(&info->free_me, 0xAA, sizeof(info->free_me));
    }

    /* Free to create UAF, then call into function that dereferences info_ptr */
    free(info);

    const char purpose_buf[4] = { 'p', 'C', 'A', '\0' };
    const char units_buf[2] = { 'u', '\0' };
    char **params = NULL;

    png_set_pCAL(png, info, purpose_buf, 0, 0, 0, 0, units_buf, params);
    return 0;
}
