#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 48) return 0;
    // Allocate heap and a node concretely
    fibheap_t heap = (fibheap_t)calloc(1, sizeof(*heap));
    if (!heap) return 0;
    fibnode_t node = (fibnode_t)calloc(1, sizeof(*node));
    if (!node) return 0;

    // Make node fields symbolic to overapproximate
    { memcpy(node, fuzz_data + 0, 48); }

    // Satisfy potential guards in the original entry (not used in neutralized harness)
    heap->min = node;   // non-NULL to mimic non-empty heap path
    heap->nodes = 1;    // reasonable non-zero

    // Call entry (neutralized to directly reach vulnerable function)
    (void)fibheap_extract_min(heap);

    return 0;
}
