/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

#ifndef SEC_INFO_TYPE_EH_FRAME
#define SEC_INFO_TYPE_EH_FRAME 1
#endif

#ifndef BUF_SIZE
#define BUF_SIZE 128
#endif

int main() {
    // Allocate core objects
    bfd *abfd = (bfd*)calloc(1, sizeof(bfd));
    struct bfd_link_info *info = (struct bfd_link_info*)calloc(1, sizeof(struct bfd_link_info));
    asection *sec = (asection*)calloc(1, sizeof(asection));

    // Contents buffer: concrete allocation, symbolic bytes
    bfd_byte *contents = (bfd_byte*)malloc(BUF_SIZE);
    { /* replay: concrete values for "contents" (128 bytes) */
    static const unsigned char contents_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(contents, contents_data, (BUF_SIZE) < 128 ? (BUF_SIZE) : 128);
  };

    // Section info and entries setup
    struct eh_frame_sec_info *sec_info = (struct eh_frame_sec_info*)calloc(1, sizeof(struct eh_frame_sec_info));
    unsigned count = 1;  // minimal count to exercise the backward pass loop
    sec_info->count = count;
    struct eh_cie_fde *entries = (struct eh_cie_fde*)calloc(count, sizeof(struct eh_cie_fde));

    // Make the single entry symbolic and constrain to hit the memmove path
    { /* replay: concrete values for "ent0" (16 bytes) */
    static const unsigned char ent0_data[] = {0x00, 0x00, 0x00, 0x08, 0xfe, 0xbf, 0xff, 0x07, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    memcpy(&entries[0], ent0_data, (sizeof(struct eh_cie_fde)) < 16 ? (sizeof(struct eh_cie_fde)) : 16);
  };
    // required conditions for the sink
    /* assume removed */
    /* assume removed */
    /* assume removed */   // reasonable cap; still allows OOB vs BUF_SIZE

    /* assume removed */

    sec_info->entry = entries;

    // Hook section fields
    sec->sec_info_type = SEC_INFO_TYPE_EH_FRAME; // benign in harness but realistic
    sec->sec_info = sec_info;                    // harness directly reads this

    // Call entry/vulnerable function (pass-through harness)
    _bfd_elf_write_section_eh_frame(abfd, info, sec, contents);

    return 0;
}
