#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

// Define globals referenced by the harness
char *g_ptr;
bfd *g_bfd;
int g_heap;

// Entry prototype from harness
bool _bfd_coff_link_input_bfd(struct coff_final_link_info *flaginfo, bfd *input_bfd);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 20) return 0;
    // Allocate output BFD and its PE data so pe_data(output_bfd) is valid
    bfd *out = (bfd *)calloc(1, sizeof(bfd));
    struct pe_data *ped = (struct pe_data *)calloc(1, sizeof(struct pe_data));
    out->pe = ped;

    // Make a small input buffer symbolic and force first byte to ','
    enum { BUF_SZ = 16 };
    char *buf = (char *)malloc(BUF_SZ);
    { memcpy(buf, fuzz_data + 0, 16); }
    /* assume removed */  // ensure we enter the if-branch so the sink assertion fires

    // Set globals consumed by the neutralized entry and dores_com
    g_ptr = buf;
    g_bfd = out;
    { memcpy(&g_heap, fuzz_data + 16, 4); }

    // Dummy inputs to the entry (not used by our neutralized pass-through)
    struct coff_final_link_info *flaginfo = (struct coff_final_link_info *)0;  // unused in neutralized entry
    bfd *input_bfd = (bfd *)calloc(1, sizeof(bfd));

    // Call entry — it will directly call dores_com with our globals
    _bfd_coff_link_input_bfd(flaginfo, input_bfd);
    return 0;
}
