/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

int main() {
    // Dummy png_struct blob (opaque in neutralized harness)
    void *pp = calloc(1, 128);
    png_struct *png_ptr = (png_struct*)pp;

    // Prepare sPLT payload
    png_sPLT_t sp;
    memset(&sp, 0, sizeof(sp));

    // Allocate a ZERO-LENGTH buffer to trigger OOB at buf[0]
    char *name = (char*)malloc(0);  // 0-sized object => any access is OOB in KLEE
    sp.name = name;                  // used as buf in harness

    sp.depth = 8;
    sp.entries = (png_sPLT_entry*)calloc(1, sizeof(png_sPLT_entry));

    // Value parameter to png_save_uint_16; arbitrary
    sp.nentries = 0x1234u;

    // Call entry (directly reaches png_save_uint_16 in harness)
    png_write_sPLT(png_ptr, &sp);
    return 0;
}
