/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

// Forward declarations matching harness signatures
typedef struct bfd bfd; // opaque
struct bfd_link_info { int dummy; };

bool _bfd_x86_elf_late_size_sections(bfd *output_bfd, struct bfd_link_info *info);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    // Opaque output_bfd buffer
    bfd *output_bfd = (bfd*) calloc(1, 64);

    // Link info as concrete allocation; make symbolic to overapproximate
    struct bfd_link_info *info = (struct bfd_link_info*) calloc(1, sizeof(struct bfd_link_info));
    { memcpy(info, fuzz_data + 0, 4); }

    // Direct call into entry (neutralized to pass-through in harness)
    (void)_bfd_x86_elf_late_size_sections(output_bfd, info);
    return 0;
}
