/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdint.h>
#include <stdlib.h>

int entry_func(uint64_t *lp);

int main() {
    // Allocate a too-small buffer so cp[1] is out-of-bounds
    unsigned char *raw = (unsigned char *)malloc(1);
    if (!raw) return 0;

    // Make buffer content symbolic (not strictly needed, but good practice)
    { /* replay: concrete values for "raw_buf" (1 bytes) */
  static const unsigned char raw_buf_data[] = {0x00};
  memcpy(raw, raw_buf_data, (1) < 1 ? (1) : 1);
};

    // Cast to uint64_t* as expected by entry_func/TIFFSwabLong8
    uint64_t *lp = (uint64_t *)raw;

    // Direct call into the entry function (pass-through to vulnerable function)
    entry_func(lp);
    return 0;
}
