/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate concrete structs
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    png_info  *info_ptr = (png_info*)calloc(1, sizeof(*info_ptr));

    if (!png_ptr || !info_ptr) return 0;

    // Prepare unknown chunks array (concrete allocation)
    unsigned int count = 2;
    png_unknown_chunk *arr = (png_unknown_chunk*)calloc(count, sizeof(*arr));
    if (!arr) return 0;

    // Make the entire array symbolic (including inline name[])
    memset(arr, 0xAA, count * sizeof(*arr));

    // Reassign pointer fields to real buffers and set sizes concretely
    arr[0].data = (unsigned char*)malloc(16);
    if (!arr[0].data) return 0;
    memset(arr[0].data, 0xAA, 16);
    arr[0].size = 16;

    arr[1].data = (unsigned char*)malloc(8);
    if (!arr[1].data) return 0;
    memset(arr[1].data, 0xAA, 8);
    arr[1].size = 8;

    // Hook into info
    info_ptr->unknown_chunks = arr;
    info_ptr->unknown_chunks_num = count;

    // Call entry (neutralized to direct call of vulnerable function)
    png_write_info_before_PLTE(png_ptr, info_ptr);

    return 0;
}
