#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdint.h>
#include <stdlib.h>

int swab_entry(uint32_t *lp);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 3) return 0;
    const size_t sz = 3;  // less than 4 to trigger cp[3] OOB
    unsigned char *buf = (unsigned char *)malloc(sz);
    if (!buf) return 0;
    { memcpy(buf, fuzz_data + 0, 3); }

    uint32_t *lp = (uint32_t *)buf;
    return swab_entry(lp);
}
