#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdint.h>
#include <stdlib.h>

int entry_func(uint64_t *lp);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 1) return 0;
    // Allocate a too-small buffer so cp[1] is out-of-bounds
    unsigned char *raw = (unsigned char *)malloc(1);
    if (!raw) return 0;

    // Make buffer content symbolic (not strictly needed, but good practice)
    { memcpy(raw, fuzz_data + 0, 1); }

    // Cast to uint64_t* as expected by entry_func/TIFFSwabLong8
    uint64_t *lp = (uint64_t *)raw;

    // Direct call into the entry function (pass-through to vulnerable function)
    entry_func(lp);
    return 0;
}
