/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

int main() {
    // Allocate concrete structs (sizes are concrete)
    png_struct *png_ptr = (png_struct *)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info  *)calloc(1, sizeof(png_info));

    // Ensure allocations succeeded
    if (!png_ptr || !info_ptr) return 0;

    // Make fields symbolic, but constrain to hit the target branch
    unsigned int trans;
    memset(&trans, 0xAA, sizeof(trans));
    // Require STRIP_ALPHA to be set so the vulnerable block executes
    #ifndef PNG_STRIP_ALPHA
    #define PNG_STRIP_ALPHA 0x1
    #endif
    /* klee_assume removed */
    png_ptr->transformations = trans;

    // Palette/num_trans fields are unused in this harness but initialize safely
    png_ptr->num_trans = 0;
    png_ptr->palette = (void*)0x1; // non-NULL inert pointer

    // Initialize info_ptr with symbolic content (value unused after free)
    memset(info_ptr, 0xAA, sizeof(*info_ptr));

    // Call entry function (pass-through to vulnerable function)
    png_read_transform_info(png_ptr, info_ptr);

    return 0;
}
