/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate parser context and input
    xmlParserCtxt *ctxt = (xmlParserCtxt *)calloc(1, sizeof(xmlParserCtxt));
    xmlParserInput *in = (xmlParserInput *)calloc(1, sizeof(xmlParserInput));

    // Small concrete buffer; we will set cur == end to trigger OOB on *in
    size_t buf_sz = 8;
    xmlChar *buf = (xmlChar *)malloc(buf_sz);
    if (!ctxt || !in || !buf) return 0;

    // Make buffer symbolic (not strictly required, but consistent with SE style)
    { /* replay: concrete values for "xml_input_buf" (8 bytes) */
  static const unsigned char xml_input_buf_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(buf, xml_input_buf_data, (buf_sz) < 8 ? (buf_sz) : 8);
};

    // Set cur and end to one-past-the-end to reproduce the bug when *in is evaluated
    in->cur = buf + buf_sz;   // points just past the allocated buffer
    in->end = buf + buf_sz;   // equal to cur so (in < e) is false, but *in already deref'd
    in->col = 0;

    ctxt->input = in;
    ctxt->options = 0; // any value is fine for this harness
    ctxt->dict = NULL;

    // Call entry (neutralized to direct-call vulnerable function)
    xmlParseElement(ctxt);

    return 0;
}
