#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdbool.h>

/* Declare entry prototype from harness */
extern bool _bfd_pe_print_private_bfd_data_common (bfd *abfd, void *vfile);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 8) return 0;
    // Allocate a minimal bfd container; fields are unused in our neutralized slice
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    if (!abfd) return 0;

    // Keep everything permissive/symbolic for KLEE exploration
    { memcpy(abfd, fuzz_data + 0, 8); }

    // Call entry directly (pass-through to vulnerable function)
    _bfd_pe_print_private_bfd_data_common(abfd, NULL);
    return 0;
}
