/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Minimal compatible forward declarations/types matching harness signatures
typedef unsigned long long bfd_vma;
typedef struct bfd { unsigned long flags; } bfd;
typedef struct asymbol { const char *name; } asymbol;
typedef struct asection { unsigned int id; } asection;
struct dwarf_debug_section { int dummy; };

// Entry function prototype
int _bfd_dwarf2_find_nearest_line_with_alt (
    bfd *abfd,
    const char *alt_filename,
    asymbol **symbols,
    asymbol *symbol,
    asection *section,
    bfd_vma offset,
    const char **filename_ptr,
    const char **functionname_ptr,
    unsigned int *linenumber_ptr,
    unsigned int *discriminator_ptr,
    const struct dwarf_debug_section *debug_sections,
    void **pinfo);

int main() {
    bfd *abfd = (bfd*)calloc(1, sizeof(bfd));
    if (!abfd) return 0;

    const char *alt_filename = NULL;
    asymbol **symbols = NULL;
    asymbol *symbol = NULL;
    asection *section = NULL;
    bfd_vma offset = 0;

    const char *filename_ptr = NULL;
    const char *functionname_ptr = NULL;
    unsigned int linenumber = 0;
    unsigned int discriminator = 0;
    const struct dwarf_debug_section *debug_sections = NULL;
    void *pinfo = NULL;

    _bfd_dwarf2_find_nearest_line_with_alt(
        abfd,
        alt_filename,
        symbols,
        symbol,
        section,
        offset,
        &filename_ptr,
        &functionname_ptr,
        &linenumber,
        &discriminator,
        debug_sections,
        &pinfo);

    return 0;
}
