/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/* Match the minimal types used in harness/syms.c */
typedef unsigned long bfd_vma;
typedef unsigned long bfd_size_type;
typedef unsigned char bfd_byte;
typedef struct bfd { int dummy; } bfd;
typedef struct asymbol { int dummy; } asymbol;
typedef struct asection { int dummy; } asection;

struct indexentry {
  bfd_vma val;
  bfd_byte *stab;
  bfd_byte *str;
  char *directory_name;
  char *file_name;
  char *function_name;
  int idx;
};

struct stab_find_info {
  asection *stabsec;
  asection *strsec;
  bfd_byte *stabs;
  bfd_byte *strs;
  struct indexentry *indextable;
  int indextablesize;
#ifdef ENABLE_CACHING
  struct indexentry *cached_indexentry;
  bfd_vma cached_offset;
  bfd_byte *cached_stab;
  char *cached_file_name;
#endif
  char *filename;
};

/* Prototype from harness */
bool _bfd_stab_section_find_nearest_line(bfd *abfd,
                                         asymbol **symbols,
                                         asection *section,
                                         bfd_vma offset,
                                         bool *pfound,
                                         const char **pfilename,
                                         const char **pfnname,
                                         unsigned int *pline,
                                         void **pinfo);

int main(void) {
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));
    asymbol **symbols = (asymbol **)calloc(1, sizeof(asymbol *));
    symbols[0] = (asymbol *)calloc(1, sizeof(asymbol));
    asection *section = (asection *)calloc(1, sizeof(asection));
    bfd_vma offset = 0;
    bool found = false;
    const char *filename = NULL;
    const char *fnname = NULL;
    unsigned int line = 0;

    struct stab_find_info *info = (struct stab_find_info *)calloc(1, sizeof(*info));
    info->stabsec = (asection *)0x1;  // non-NULL per preconditions
    info->strsec = (asection *)0x1;   // non-NULL per preconditions
    info->indextablesize = 0;         // drive the vulnerable path in harness

    info->stabs = (bfd_byte *)malloc(32);
    info->strs  = (bfd_byte *)malloc(16);
    if (info->stabs) memset(info->stabs, 0x41, 32);
    if (info->strs)  memset(info->strs,  0x42, 16);

    void *pinfo = info;  // pass by reference

    (void)_bfd_stab_section_find_nearest_line(
        abfd, symbols, section, offset,
        &found, &filename, &fnname, &line,
        &pinfo);

    return 0;
}
