#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>

#ifndef XML_SCHEMA_TYPE_ALL
#define XML_SCHEMA_TYPE_ALL 1
#endif

/* Keep local typedefs consistent with harness/spine.c */
typedef unsigned char xmlChar;
typedef int xmlParserErrors;

struct _xmlNode { struct _xmlNode *next; };
typedef struct _xmlNode* xmlNodePtr;

struct _xmlSchemaAbstractCtxt { int instate; };
typedef struct _xmlSchemaAbstractCtxt* xmlSchemaAbstractCtxtPtr;

typedef void* xmlSchemaTypePtr;

int xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                            xmlParserErrors error,
                            xmlNodePtr node,
                            xmlSchemaTypePtr type,
                            const char *message,
                            int nbval,
                            int nbneg,
                            xmlChar **values);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 4) return 0;
    // Allocate and initialize context
    struct _xmlSchemaAbstractCtxt *ctxt = (struct _xmlSchemaAbstractCtxt *)calloc(1, sizeof(*ctxt));

    // Set instate symbolically and constrain to the target case
    int sym_instate;
    { memcpy(&sym_instate, fuzz_data + 0, 4); }
    
    ctxt->instate = sym_instate;

    // Build a simple xmlNode chain: node -> next
    struct _xmlNode *node = (struct _xmlNode *)malloc(sizeof(*node));
    memset(node, 0, sizeof(*node));
    struct _xmlNode *next = (struct _xmlNode *)malloc(sizeof(*next));
    memset(next, 0, sizeof(*next));
    node->next = next;

    // Other params (not used by our slice)
    int error = 0;
    const char *message = "msg";
    xmlChar *vals_arr_local[1] = { NULL };
    xmlChar **values = (xmlChar **)vals_arr_local;

    // Direct call to the entry/vulnerable function
    xmlSchemaComplexTypeErr(ctxt, error, node, NULL, message, 0, 0, values);
    return 0;
}
