#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* harness/spine.c */

/* Minimal local type definitions to avoid pulling project headers */
#ifndef XML_SCHEMA_TYPE_ALL
#define XML_SCHEMA_TYPE_ALL 1
#endif
#ifndef XML_SCHEMA_TYPE_SEQUENCE
#define XML_SCHEMA_TYPE_SEQUENCE 2
#endif
#ifndef XML_SCHEMA_TYPE_CHOICE
#define XML_SCHEMA_TYPE_CHOICE 3
#endif

typedef unsigned char xmlChar;
typedef int xmlParserErrors;

/* Minimal xmlNode with only the field we need */
struct _xmlNode { struct _xmlNode *next; };
typedef struct _xmlNode* xmlNodePtr;

/* Minimal abstract ctxt with only the state field we need */
struct _xmlSchemaAbstractCtxt { int instate; };
typedef struct _xmlSchemaAbstractCtxt* xmlSchemaAbstractCtxtPtr;

typedef void* xmlSchemaTypePtr; /* unused in our slice */
#define ATTRIBUTE_UNUSED

/* Forward decl to satisfy the spine symbol (not used on path) */

/* Entry == Vulnerable function — neutralized to keep only the target case */
int xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                            xmlParserErrors error,
                            xmlNodePtr node,
                            xmlSchemaTypePtr type ATTRIBUTE_UNUSED,
                            const char *message,
                            int nbval,
                            int nbneg,
                            xmlChar **values) {
    (void)error; (void)type; (void)message; (void)nbval; (void)nbneg; (void)values;

    /* Local setup for the vulnerable statement */
    xmlNodePtr child = node; /* child sourced from caller */
