#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 8) return 0;
    // Allocate bfd object
    bfd *abfd = (bfd *)calloc(1, sizeof(bfd));

    // Prepare parameters
    long count = 1;
    long relsize = 4;
    bfd_vma got_addr = 0;
    { memcpy(&got_addr, fuzz_data + 0, 8); }

    // Prepare plts array with one element
    struct elf_x86_plt *plts = (struct elf_x86_plt *)calloc(1, sizeof(struct elf_x86_plt));
    plts[0].sec = (struct fake_sec *)calloc(1, sizeof(struct fake_sec));
    plts[0].sec->vma = 0;
    plts[0].plt_got_insn_size = 0;
    plts[0].count = 1;

    // dynsyms and ret arrays (not used by harness, but allocate to satisfy signature)
    asymbol **dynsyms = (asymbol **)calloc(1, sizeof(asymbol *));
    asymbol **ret = (asymbol **)calloc(1, sizeof(asymbol *));
    dynsyms[0] = (asymbol *)calloc(1, sizeof(asymbol));
    ret[0] = (asymbol *)calloc(1, sizeof(asymbol));
    dynsyms[0]->name = "sym0";
    ret[0]->name = "retsym0";

    // Call the entry/vulnerable function directly
    _bfd_x86_elf_get_synthetic_symtab(abfd, count, relsize, got_addr, plts, dynsyms, ret);

    return 0;
}
