/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

typedef unsigned char xmlChar;
typedef int xmlParserErrors;

typedef struct _xmlSchemaAbstractCtxt { int dummy; } *xmlSchemaAbstractCtxtPtr;
typedef struct _xmlNode { int dummy; } *xmlNodePtr;
typedef struct _xmlSchemaType { int type; } *xmlSchemaTypePtr;

int xmlSchemaComplexTypeErr(xmlSchemaAbstractCtxtPtr actxt,
                            xmlParserErrors error,
                            xmlNodePtr node,
                            xmlSchemaTypePtr type,
                            const char *message,
                            int nbval,
                            int nbneg,
                            xmlChar **values);

int main(void) {
    // Allocate concrete objects for parameters
    xmlSchemaAbstractCtxtPtr actxt = (xmlSchemaAbstractCtxtPtr)calloc(1, sizeof(struct _xmlSchemaAbstractCtxt));
    xmlNodePtr node = (xmlNodePtr)calloc(1, sizeof(struct _xmlNode));
    xmlSchemaTypePtr type = (xmlSchemaTypePtr)calloc(1, sizeof(struct _xmlSchemaType));

    // Symbolic message buffer
    char *message = (char *)malloc(64);
    { /* replay: concrete values for "message" (64 bytes) */
  static const unsigned char message_data[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  memcpy(message, message_data, (64) < 64 ? (64) : 64);
};

    // Symbolic nbval to steer index; allow OOB vs array size 4
    int nbval;
    { /* replay: concrete values for "nbval" (4 bytes) */
  static const unsigned char nbval_data[] = {0x04, 0x00, 0x00, 0x00};
  memcpy(&nbval, nbval_data, (sizeof(nbval)) < 4 ? (sizeof(nbval)) : 4);
};
    /* klee_assume removed for replay */
    /* klee_assume removed for replay */

    int nbneg = 0;
    xmlParserErrors error = 0;

    // Prepare values array with small concrete size
    const size_t arr_sz = 4;
    xmlChar **values = (xmlChar **)malloc(arr_sz * sizeof(xmlChar *));
    for (size_t i = 0; i < arr_sz; i++) {
        values[i] = (xmlChar *)malloc(2);
        { /* replay: concrete values for "valbytes" (2 bytes) */
  static const unsigned char valbytes_data[] = {0x00, 0x00};
  memcpy(values[i], valbytes_data, (2) < 2 ? (2) : 2);
};
    }

    // Direct call to entry function
    xmlSchemaComplexTypeErr(actxt, error, node, type, message, nbval, nbneg, values);
    return 0;
}
