/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdint.h>
#include <stdlib.h>

/* Match the harness opaque type name */
typedef struct png_struct_def png_struct;

/* Declare the entry/vulnerable function */
extern void png_write_chunk_start(png_struct *png_ptr, const unsigned char *chunk_string, unsigned int length);

int main() {
    // Allocate a too-short buffer (2 bytes) for chunk_string; PNG_CHUNK_FROM_STRING reads 4 bytes
    unsigned char *chunk_string = (unsigned char*)malloc(2);
    memset(chunk_string, 0xAA, 2);

    // Length is unrelated to the macro read; keep it symbolic
    unsigned int length;
    memset(&length, 0xAA, sizeof(length));

    // png_ptr is unused in our neutralized harness; pass NULL
    png_struct *png_ptr = (png_struct*)0;

    // Direct call to the vulnerable function
    png_write_chunk_start(png_ptr, chunk_string, length);
    return 0;
}
