/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <stdint.h>

// Decls from harness
void png_handle_fcTL(png_struct *png_ptr, png_info *info_ptr, png_uint_32 length);

int main() {
    // Allocate concrete instances
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(png_struct));
    png_info *info_ptr = (png_info*)calloc(1, sizeof(png_info));

    if (!png_ptr || !info_ptr) return 0;

    // Make relevant fields symbolic to give KLEE freedom
    if (info_ptr) {
        memset(&info_ptr->next_frame_width, 0xAA, sizeof(info_ptr->next_frame_width));
    }

    // Length is irrelevant in neutralized entry, but set to expected 26
    png_uint_32 length = 26;

    // Call entry (directly passes through to vulnerable function in harness)
    png_handle_fcTL(png_ptr, info_ptr, length);

    return 0;
}
