#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Forward declaration from harness/uri.c
int xmlNormalizeURIPath(char *path);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 2) return 0;
    // Allocate a small, non-NUL-terminated buffer to trigger cur[2] OOB read
    char *path = (char *)malloc(2);
    if (!path) return 0;

    // Make the 2 bytes symbolic and steer to the '..' pattern
    { memcpy(path, fuzz_data + 0, 2); }
    
    

    // Call entry directly (pure pass-through to xmlNormalizePath)
    (void)xmlNormalizeURIPath(path);
    return 0;
}
