/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <stdint.h>

// Forward declaration from harness/uri.c
int xmlNormalizeURIPath(char *path);

int main() {
    // Allocate a small, non-NUL-terminated buffer to trigger cur[2] OOB read
    char *path = (char *)malloc(2);
    if (!path) return 0;

    // Make the 2 bytes symbolic and steer to the '..' pattern
    { /* replay: concrete values for "path_bytes" (2 bytes) */
  static const unsigned char path_bytes_data[] = {0x2e, 0x2e};
  memcpy(path, path_bytes_data, (2) < 2 ? (2) : 2);
};
    /* klee_assume removed for replay */
    /* klee_assume removed for replay */

    // Call entry directly (pure pass-through to xmlNormalizePath)
    (void)xmlNormalizeURIPath(path);
    return 0;
}
