/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <string.h>
#include <stddef.h>

struct dyn_string {
    char *s;
    int length;
    int allocated;
};
typedef struct dyn_string* dyn_string_t;

void dyn_string_clear(dyn_string_t ds);

int main() {
    dyn_string_t ds = (dyn_string_t)calloc(1, sizeof(*ds));
    if (!ds) return 0;

    const size_t BUF_SIZE = 16;
    char *buf = (char *)malloc(BUF_SIZE);
    if (!buf) return 0;

    memset(buf, 'A', BUF_SIZE);
    buf[0] = 'B';
    ds->s = buf;
    ds->allocated = (int)BUF_SIZE;
    ds->length = 1; // preconditions before clear

    // Free internal buffer to create UAF, keep ds->s dangling
    free(buf);

    // Call into vulnerable function (defined in harness)
    dyn_string_clear(ds);

    return 0;
}
