#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>

/* Mirror minimal types from harness/xmlschemas.c */
typedef unsigned char xmlChar;

typedef struct _xmlNode { void *dummy; } *xmlNodePtr;

typedef struct _xmlSchemaRedef {
    const xmlChar *refTargetNs;
    const xmlChar *refName;
    void *reference;
} xmlSchemaRedef, *xmlSchemaRedefPtr;

typedef struct _xmlSchemaParserCtxt {
    xmlSchemaRedefPtr redef;
    int redefCounter;
} xmlSchemaParserCtxt, *xmlSchemaParserCtxtPtr;

/* Entry function prototype (defined in harness) */
void xmlSchemaComplexTypeErr(void *actxt,
                             int error,
                             xmlNodePtr node,
                             void *type,
                             const char *message,
                             int nbval,
                             int nbneg,
                             xmlChar **values);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 128) return 0;
    // Allocate parser context concretely
    xmlSchemaParserCtxtPtr ctxt = (xmlSchemaParserCtxtPtr)calloc(1, sizeof(*ctxt));
    if (!ctxt) return 0;

    // Allocate the Redef object that will be freed inside the vulnerable function
    xmlSchemaRedefPtr redef = (xmlSchemaRedefPtr)calloc(1, sizeof(*redef));
    if (!redef) return 0;

    // Prepare name components backed by real memory; make contents symbolic
    size_t buf_sz = 64; // concrete size
    xmlChar *ns  = (xmlChar *)malloc(buf_sz);
    xmlChar *name = (xmlChar *)malloc(buf_sz);
    if (!ns || !name) return 0;
    { memcpy(ns, fuzz_data + 0, 64); }
    { memcpy(name, fuzz_data + 64, 64); }

    // Fill struct fields
    redef->refTargetNs = ns;
    redef->refName = name;
    ctxt->redef = redef;
    ctxt->redefCounter = 0;

    // Node argument: allocate a dummy node object so entry preconditions about non-NULL are satisfied
    xmlNodePtr node = (xmlNodePtr)calloc(1, sizeof(*node));

    // Call entry directly (pass-through to vulnerable function)
    xmlSchemaComplexTypeErr((void*)ctxt, 0, node, NULL, "msg", 0, 0, NULL);

    return 0;
}
