#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glob.h>

#ifndef ATTRIBUTE_UNUSED
#define ATTRIBUTE_UNUSED __attribute__((unused))
#endif

/* Minimal stand-ins for libxml2 schema types */
typedef void* xmlSchemaParserCtxtPtr;
typedef void* xmlSchemaPtr;

/* Global test harness state expected by runtest.c */
int nb_tests = 0;
int testErrorsSize = 0;
char testErrors[1024];

/* Stubs for libxml2 functions used by schemasTest */
xmlSchemaParserCtxtPtr xmlSchemaNewParserCtxt(const char *filename ATTRIBUTE_UNUSED) {
    return (xmlSchemaParserCtxtPtr)0x1;
}

void testStructuredErrorHandler(void *userData ATTRIBUTE_UNUSED, void *error ATTRIBUTE_UNUSED) {
    /* no-op */
}

void xmlSchemaSetParserStructuredErrors(xmlSchemaParserCtxtPtr ctxt ATTRIBUTE_UNUSED,
                                        void (*handler)(void*, void*),
                                        void *userData) {
    /* call once to avoid unused warnings */
    if (handler) handler(userData, NULL);
}

xmlSchemaPtr xmlSchemaParse(xmlSchemaParserCtxtPtr ctxt ATTRIBUTE_UNUSED) {
    return (xmlSchemaPtr)0x2;
}

void xmlSchemaFreeParserCtxt(xmlSchemaParserCtxtPtr ctxt ATTRIBUTE_UNUSED) { }
void xmlSchemaFree(xmlSchemaPtr schema ATTRIBUTE_UNUSED) { }

/* Stub for the per-test executor */
int schemasOneTest(const char *filename ATTRIBUTE_UNUSED,
                   const char *instance ATTRIBUTE_UNUSED,
                   const char *err ATTRIBUTE_UNUSED,
                   int options ATTRIBUTE_UNUSED,
                   xmlSchemaPtr schemas ATTRIBUTE_UNUSED) {
    return 0;
}

/* Mimic baseFilename from runtest.c: return last path segment */
static const char *baseFilename(const char *filename) {
    const char *base = strrchr(filename, '/');
    if (base) return base + 1;
    return filename;
}

/* Vulnerable function copied/adapted from runtest.c */
static int schemasTest(const char *filename,
                       const char *resul ATTRIBUTE_UNUSED,
                       const char *errr ATTRIBUTE_UNUSED,
                       int options) {
    const char *base = baseFilename(filename);
    const char *base2;
    const char *instance;
    xmlSchemaParserCtxtPtr ctxt;
    xmlSchemaPtr schemas;
    int res = 0, len, ret;
    int parseErrorsSize;
    char pattern[500];
    char prefix[500];
    char err[500];
    glob_t globbuf;
    size_t i;
    char count = 0;

    /* first compile the schemas if possible */
    ctxt = xmlSchemaNewParserCtxt(filename);
    xmlSchemaSetParserStructuredErrors(ctxt, testStructuredErrorHandler, NULL);
    schemas = xmlSchemaParse(ctxt);
    xmlSchemaFreeParserCtxt(ctxt);
    parseErrorsSize = testErrorsSize;

    /* most of the mess is about the output filenames generated by the Makefile */
    len = (int)strlen(base);
    if ((len > 499) || (len < 5)) {
        xmlSchemaFree(schemas);
        return(-1);
    }
    len -= 4; /* remove trailing .xsd */
    if (base[len - 2] == '_') { /* first unsafe check (requires len >= 2) */
        len -= 2; /* remove subtest number */
    }
    if (base[len - 2] == '_') { /* second unsafe check: OOB read when len == 1 */
        len -= 2; /* remove subtest number */
    }
    memcpy(prefix, base, (size_t)len);
    prefix[len] = 0;

    if (snprintf(pattern, 499, "./test/schemas/%s_*.xml", prefix) >= 499)
        pattern[499] = 0;

    if (base[len] == '_') {
        len += 2;
        memcpy(prefix, base, (size_t)len);
        prefix[len] = 0;
    }

    globbuf.gl_offs = 0;
    glob(pattern, GLOB_DOOFFS, NULL, &globbuf);
    for (i = 0; i < globbuf.gl_pathc; i++) {
        testErrorsSize = parseErrorsSize;
        testErrors[parseErrorsSize] = 0;
        instance = globbuf.gl_pathv[i];
        base2 = baseFilename(instance);
        len = (int)strlen(base2);
        if ((len > 6) && (base2[len - 6] == '_')) {
            count = base2[len - 5];
            ret = snprintf(err, 499, "result/schemas/%s_%c.err", prefix, count);
            if (ret >= 499)
                err[499] = 0;
        } else {
            fprintf(stderr, "don't know how to process %s\n", instance);
            continue;
        }

        nb_tests++;
        ret = schemasOneTest(filename, instance, err, options, schemas);
        if (ret != 0)
            res = ret;
    }
    globfree(&globbuf);
    xmlSchemaFree(schemas);
    return res;
}

int main(void) {
    /* Craft filename whose base is exactly 5 chars: "a.xsd" */
    const char *src = "a.xsd"; /* len == 5 */
    size_t n = strlen(src) + 1;
    char *fname = (char *)malloc(n);
    if (!fname) return 1;
    memcpy(fname, src, n);

    /* Call vulnerable function: after removing ".xsd", len == 1, then base[len-2] reads base[-1] */
    (void)schemasTest(fname, NULL, NULL, 0);

    free(fname);
    return 0;
}
