/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>

// Minimal forward declarations matching harness signatures
typedef unsigned char xmlChar;
typedef int xmlCharEncoding;
typedef struct _xmlSAXHandler xmlSAXHandler;
typedef struct _xmlParserInputBuffer xmlParserInputBuffer;
typedef struct _xmlDtd xmlDtd;

struct _xmlSAXHandler { int _pad; };
struct _xmlParserInputBuffer { int _pad; };

// Prototype from harness
xmlDtd * xmlIOParseDTD(xmlSAXHandler *sax, xmlParserInputBuffer *input, xmlCharEncoding enc);

int main() {
    xmlSAXHandler *sax = (xmlSAXHandler*)calloc(1, sizeof(xmlSAXHandler));
    xmlParserInputBuffer *input = (xmlParserInputBuffer*)calloc(1, sizeof(xmlParserInputBuffer));
    xmlCharEncoding enc;
    { /* replay: concrete values for "enc" (4 bytes) */
  static const unsigned char enc_data[] = {0x00, 0x00, 0x00, 0x00};
  memcpy(&enc, enc_data, (sizeof(enc)) < 4 ? (sizeof(enc)) : 4);
};

    // Ensure non-NULL to pass entry guards (if any)
    /* klee_assume removed for replay */
    /* klee_assume removed for replay */

    xmlDtd *ret = xmlIOParseDTD(sax, input, enc);
    (void)ret;
    return 0;
}
