/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>

#ifndef PNG_INFO_pHYs
#define PNG_INFO_pHYs 0x0001u
#endif
#ifndef PNG_RESOLUTION_METER
#define PNG_RESOLUTION_METER 1
#endif

extern png_uint_32 png_get_pixels_per_inch(const png_struct *png_ptr, const png_info *info_ptr);

int main() {
    // Allocate concrete structs
    png_struct *png_ptr = (png_struct *)calloc(1, sizeof(png_struct));
    png_info  *info_ptr = (png_info  *)calloc(1, sizeof(png_info));
    if (!png_ptr || !info_ptr) return 0;

    // Initialize fields (not strictly needed for UAF, but set to plausible values)
    info_ptr->valid = PNG_INFO_pHYs;
    info_ptr->phys_unit_type = PNG_RESOLUTION_METER;
    info_ptr->x_pixels_per_unit = 2835;
    info_ptr->y_pixels_per_unit = 2835;

    // Trigger UAF: free info_ptr to make it a stale pointer
    free(info_ptr);

    // Call entry; vulnerable function will dereference info_ptr->valid
    (void)png_get_pixels_per_inch(png_ptr, info_ptr);
    return 0;
}
