#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdint.h>
#include <stdlib.h>

int entry_func(uint32_t *lp);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 2) return 0;
    // Allocate fewer than 3 bytes so that cp[2] is out-of-bounds
    unsigned char *buf = (unsigned char *)malloc(2);
    if (!buf) return 0;
    { memcpy(buf, fuzz_data + 0, 2); }

    // Call entry with an undersized buffer cast to uint32_t*
    entry_func((uint32_t *)buf);
    return 0;
}
