/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdint.h>
#include <stdlib.h>

/* Provide minimal compatible declarations (opaque types + typedefs) */
typedef uint32_t png_uint_32;
typedef struct png_struct png_struct;  /* opaque */
typedef struct png_info png_info;      /* opaque */

/* Declare the target function (matching harness signature) */
void png_write_reinit(png_struct *png_ptr, png_info *info_ptr,
                      png_uint_32 width, png_uint_32 height);

int main() {
    /* Allocate opaque objects as byte buffers and cast */
    png_struct *png_ptr = (png_struct*)malloc(256);
    if (!png_ptr) return 0;

    void *info_live_buf = malloc(256);
    if (!info_live_buf) return 0;
    png_info *info_live = (png_info*)info_live_buf;

    /* Symbolize the bytes backing info_live so field reads vary */
    memset(info_live_buf, 0xAA, 256);

    /* Create a stale alias and free the backing buffer (UAF setup) */
    png_info *info_ptr = info_live;  /* alias retained */
    free(info_live_buf);             /* now info_ptr is dangling */

    /* Width/height symbolic */
    png_uint_32 width, height;
    memset(&width, 0xAA, sizeof(width));
    memset(&height, 0xAA, sizeof(height));

    /* Direct call to entry/vulnerable function */
    png_write_reinit(png_ptr, info_ptr, width, height);
    return 0;
}
