#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* Minimal sliced harness for libxml2 relaxng recursion site */

/* Minimal type universe */
typedef unsigned char xmlChar;

typedef struct _xmlNs {
    const xmlChar *href;
} xmlNs, *xmlNsPtr;

typedef struct _xmlAttr xmlAttr;
typedef xmlAttr *xmlAttrPtr;
struct _xmlAttr {
    const xmlChar *name;
    xmlNsPtr ns;
    xmlAttrPtr next;
};

typedef struct _xmlNode xmlNode;
struct _xmlNode {
    struct _xmlNode *parent;
    xmlAttrPtr properties;
};

typedef struct _xmlDoc xmlDoc;
struct _xmlDoc { int dummy; };

typedef struct _xmlRelaxNGDefine xmlRelaxNGDefine;
typedef xmlRelaxNGDefine *xmlRelaxNGDefinePtr;
struct _xmlRelaxNGDefine {
    int type;
    const xmlChar *name;
    const xmlChar *ns;
    xmlRelaxNGDefinePtr nameClass;
    xmlRelaxNGDefinePtr content;
    xmlRelaxNGDefinePtr next;
};

typedef struct _xmlRelaxNGValidCtxt xmlRelaxNGValidCtxt;
typedef xmlRelaxNGValidCtxt *xmlRelaxNGValidCtxtPtr;
struct _xmlRelaxNGValidCtxt {
    xmlRelaxNGDefinePtr pdef;
    void *state;
    int errNo;
    int flags;
    int instate;
};

/* Vulnerable function — keep the recursive call line verbatim */
static int
xmlRelaxNGAttributeMatch(xmlRelaxNGValidCtxtPtr ctxt,
