/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES
#include <stdlib.h>

/* Mirror minimal types from harness/relaxng.c */
typedef unsigned char xmlChar;

typedef struct _xmlNs { const xmlChar *href; } xmlNs, *xmlNsPtr;

typedef struct _xmlAttr xmlAttr; typedef xmlAttr *xmlAttrPtr;
struct _xmlAttr { const xmlChar *name; xmlNsPtr ns; xmlAttrPtr next; };

typedef struct _xmlNode xmlNode; struct _xmlNode { struct _xmlNode *parent; xmlAttrPtr properties; };

typedef struct _xmlDoc { int dummy; } xmlDoc;

typedef struct _xmlRelaxNGDefine xmlRelaxNGDefine; typedef xmlRelaxNGDefine *xmlRelaxNGDefinePtr;
struct _xmlRelaxNGDefine { int type; const xmlChar *name; const xmlChar *ns; xmlRelaxNGDefinePtr nameClass; xmlRelaxNGDefinePtr content; xmlRelaxNGDefinePtr next; };

typedef struct _xmlRelaxNGValidCtxt xmlRelaxNGValidCtxt; typedef xmlRelaxNGValidCtxt *xmlRelaxNGValidCtxtPtr;
struct _xmlRelaxNGValidCtxt { xmlRelaxNGDefinePtr pdef; void *state; int errNo; int flags; int instate; };

int xmlRelaxNGValidateFullElement(xmlRelaxNGValidCtxt *ctxt, xmlDoc *doc, xmlNode *elem);

int main() {
    xmlRelaxNGValidCtxt *ctxt = (xmlRelaxNGValidCtxt *)calloc(1, sizeof(*ctxt));
    if (!ctxt) return 1;

    xmlRelaxNGDefine *root = (xmlRelaxNGDefine *)calloc(1, sizeof(*root));
    xmlRelaxNGDefine *child = (xmlRelaxNGDefine *)calloc(1, sizeof(*child));
    if (!root || !child) return 1;
    root->content = child;    // ensures list != NULL in top frame
    child->content = NULL;    // base case: recursive call returns immediately
    child->next = NULL;       // terminate list
    root->next = NULL;

    ctxt->pdef = root;

    xmlNode *elem = (xmlNode *)calloc(1, sizeof(*elem));
    if (!elem) return 1;

    (void)xmlRelaxNGValidateFullElement(ctxt, (xmlDoc *)NULL, elem);
    return 0;
}
