#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdint.h>
#include <stdlib.h>

int entry_func(uint64_t *lp); // from harness/tif_swab.c

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 6) return 0;
    // Allocate a too-small buffer so that cp[6] is OOB (needs 7 bytes)
    size_t sz = 6; // concrete size per instructions
    unsigned char *buf = (unsigned char*)malloc(sz);
    if (!buf) return 0;

    // Make buffer contents symbolic (size is concrete)
    { memcpy(buf, fuzz_data + 0, 6); }

    // Cast to uint64_t* as expected by entry_func/TIFFSwabLong8
    uint64_t *lp = (uint64_t*)buf;

    // Direct call to entry function
    entry_func(lp);
    return 0;
}
