/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate parser context and input
    htmlParserCtxt *ctxt = (htmlParserCtxt *)calloc(1, sizeof(htmlParserCtxt));
    xmlParserInput *in = (xmlParserInput *)calloc(1, sizeof(xmlParserInput));

    // Small buffer: "<!" so avail == 2 < 4, but code will still read cur[2], cur[3] when terminate==1
    const size_t buf_sz = 2;
    xmlChar *buf = (xmlChar *)malloc(buf_sz);
    buf[0] = '<';
    buf[1] = '!';

    // Wire input pointers
    in->base = buf;
    in->cur = buf;           // start at beginning
    in->end = buf + buf_sz;  // avail = 2

    // Install input into context
    ctxt->input = in;

    // Make instate symbolic and constrain to XML_PARSER_CONTENT per driver_hint
    int sym_instate;
    { /* replay: concrete values for "instate" (4 bytes) */
  static const unsigned char instate_data[] = {0x04, 0x00, 0x00, 0x00};
  memcpy(&sym_instate, instate_data, (sizeof(sym_instate)) < 4 ? (sizeof(sym_instate)) : 4);
};
    /* klee_assume removed for replay */
    ctxt->instate = sym_instate;

    // errNo must be 0 to avoid early returns in real code paths (safe default)
    ctxt->errNo = 0;

    // terminate==1 triggers the vulnerable path (no avail<4 early return)
    int terminate = 1;

    // Call entry function (harness version is direct pass-through)
    htmlParseChunk(ctxt, /*chunk*/ NULL, /*size*/ 0, terminate);

    return 0;
}
