#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <stdint.h>

// Prototype from harness
void TIFFSwabArrayOfFloat(float *fp, tmsize_t n);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 3) return 0;
    // Allocate a too-small buffer (3 bytes) so cp[3] is out-of-bounds
    size_t sz = 3;  // concrete size per instructions
    unsigned char *buf = (unsigned char *)malloc(sz);
    if (!buf) return 0;

    // Make buffer content symbolic (values don't matter for OOB trigger)
    { memcpy(buf, fuzz_data + 0, 3); }

    // Call vulnerable function with n = 1 (process one float)
    TIFFSwabArrayOfFloat((float *)buf, (tmsize_t)1);

    return 0;
}
