#pragma once
/* Merged harness_types.h — upstream headers + agent definitions */
/* Generated by concrete_verify.py */

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/relaxng.h>
#include <libxml/valid.h>
#include <libxml/xpath.h>
#include <libxml/xpointer.h>
#include <libxml/catalog.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlwriter.h>
#include <libxml/list.h>
#include <libxml/hash.h>
#include <libxml/dict.h>
#include <libxml/entities.h>
#include <libxml/uri.h>
#include <libxml/c14n.h>
#include <libxml/xinclude.h>
#include <libxml/HTMLparser.h>
#include <libxml/HTMLtree.h>
#include <libxml/debugXML.h>
#include <libxml/xmlstring.h>
#include <libxml/xmlmemory.h>
#include <libxml/threads.h>
#include <libxml/xmlIO.h>
#include <libxml/xmlsave.h>
#include <libxml/xmlregexp.h>
#include <libxml/pattern.h>
#include <libxml/xmlerror.h>
#include <libxml/parserInternals.h>
#include <libxml/globals.h>
#include "libxml.h"

/* ── Agent-defined types (for internal/private types not in public headers) ── */


/* Minimal neutralized harness for libxml2 relaxng CWE-674 */

/* Forward decls and typedefs to keep only what we need */
typedef struct _xmlRelaxNGParserCtxt xmlRelaxNGParserCtxt;
typedef struct _xmlRelaxNGDefine xmlRelaxNGDefine;

typedef xmlRelaxNGParserCtxt * xmlRelaxNGParserCtxtPtr;
typedef xmlRelaxNGDefine * xmlRelaxNGDefinePtr;

typedef enum {
    XML_RELAXNG_CONTENT_EMPTY = 0,
    XML_RELAXNG_CONTENT_SIMPLE = 1,
    XML_RELAXNG_CONTENT_COMPLEX = 2,
    XML_RELAXNG_CONTENT_ERROR = 3
} xmlRelaxNGContentType;

/* Model only the minimal type selector used on path */
typedef enum {
    XML_RELAXNG_RECURSE = 1,   /* synthetic value to drive recursion */
    XML_RELAXNG_TEXT = 2       /* synthetic non-recursive leaf */
} xmlRelaxNGType;

struct _xmlRelaxNGDefine {
    xmlRelaxNGDefinePtr content;
    xmlRelaxNGType type;
    void *node;
};

struct _xmlRelaxNGParserCtxt {
    xmlRelaxNGDefinePtr cur;
    int flags;
    xmlRelaxNGType ptype;
};

typedef struct _xmlRelaxNG xmlRelaxNG; struct _xmlRelaxNG { int dummy; };
typedef xmlRelaxNG * xmlRelaxNGPtr;

/* VULNERABLE FUNCTION (neutralized, keep only target path and exact sink line) */
static xmlRelaxNGContentType xmlRelaxNGCheckRules(xmlRelaxNGParserCtxtPtr ctxt,
                                                  xmlRelaxNGDefinePtr cur,
                                                  int flags,
                                                  xmlRelaxNGType ptype)
{
