/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
// NO_HARNESS_TYPES

#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Mirror the minimal types used in harness/relaxng.c */
typedef struct _xmlRelaxNGParserCtxt xmlRelaxNGParserCtxt;
typedef struct _xmlRelaxNGDefine xmlRelaxNGDefine;

typedef xmlRelaxNGParserCtxt * xmlRelaxNGParserCtxtPtr;
typedef xmlRelaxNGDefine * xmlRelaxNGDefinePtr;

typedef enum {
    XML_RELAXNG_CONTENT_EMPTY = 0,
    XML_RELAXNG_CONTENT_SIMPLE = 1,
    XML_RELAXNG_CONTENT_COMPLEX = 2,
    XML_RELAXNG_CONTENT_ERROR = 3
} xmlRelaxNGContentType;

typedef enum {
    XML_RELAXNG_RECURSE = 1,
    XML_RELAXNG_TEXT = 2
} xmlRelaxNGType;

struct _xmlRelaxNGDefine {
    xmlRelaxNGDefinePtr content;
    xmlRelaxNGType type;
    void *node;
};

struct _xmlRelaxNGParserCtxt {
    xmlRelaxNGDefinePtr cur;
    int flags;
    xmlRelaxNGType ptype;
};

typedef struct _xmlRelaxNG xmlRelaxNG; struct _xmlRelaxNG { int dummy; };
typedef xmlRelaxNG * xmlRelaxNGPtr;

/* Entry function prototype from harness */
xmlRelaxNG * xmlRelaxNGParse(xmlRelaxNGParserCtxt *ctxt);

int main(void) {
    // Allocate parser context
    xmlRelaxNGParserCtxt *ctxt = (xmlRelaxNGParserCtxt *)calloc(1, sizeof(*ctxt));
    if (!ctxt) return 0;

    // Build a minimal define graph: parent (RECURSE) -> child (TEXT)
    xmlRelaxNGDefine *parent = (xmlRelaxNGDefine *)calloc(1, sizeof(*parent));
    xmlRelaxNGDefine *child  = (xmlRelaxNGDefine *)calloc(1, sizeof(*child));
    if (!parent || !child) return 0;

    parent->type = XML_RELAXNG_RECURSE;
    parent->content = child;

    child->type = XML_RELAXNG_TEXT;
    child->content = NULL;

    // Hook into context
    ctxt->cur = parent;
    ctxt->flags = 0;
    ctxt->ptype = XML_RELAXNG_RECURSE;

    // Call entry
    xmlRelaxNGParse(ctxt);

    return 0;
}
