/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
// NO_HARNESS_TYPES
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

// Minimal local typedefs to match harness/pngwutil.c
typedef unsigned char png_byte;
typedef unsigned int png_uint_32;
typedef struct { int dummy; } png_struct;

// Prototype from harness
void png_write_chunk(png_struct *png_ptr, const png_byte *chunk_string,
                     const png_byte *data, size_t length);

int main() {
    // Concrete allocation for png_struct
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));

    // Allocate a chunk_string with 3 bytes (<4) to exercise PNG_CHUNK_FROM_STRING indexing
    size_t chunk_len = 3; // concrete size
    png_byte *chunk_string = (png_byte*)malloc(chunk_len);
    memset(chunk_string, 0xAA, chunk_len);

    // Data buffer (concrete size)
    size_t data_len = 8;
    png_byte *data = (png_byte*)malloc(data_len);
    memset(data, 0xAA, data_len);

    // Direct call to entry/vul function
    png_write_chunk(png_ptr, chunk_string, data, data_len);
    return 0;
}
