/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

// Stub for the release_write callback signature
static void release_write_stub(void *data) {
    // Do nothing; if we reach here, universal sink assert will fire after call
    (void)data;
}

int main() {
    // Allocate a write-object layout (we will cast it to simple_object_read* on call)
    simple_object_write *w = (simple_object_write*)calloc(1, sizeof(simple_object_write));
    if (!w) return 0;

    // Allocate a functions vtable and set the callback
    simple_object_functions *funcs = (simple_object_functions*)calloc(1, sizeof(simple_object_functions));
    if (!funcs) return 0;
    funcs->release_write = release_write_stub;

    // Attach to object
    w->functions = funcs;

    // Allocate some data payload
    void *payload = calloc(1, 16);
    w->data = payload;

    // Create UAF: free the functions table so dereference in vulnerable statement becomes use-after-free
    free(funcs);

    // Prepare dummy params for entry (not used due to neutralized entry)
    const char *dest = "out.o";
    int err = 0;
    int rename = 0;

    // Call entry — it directly calls simple_object_release_write casting sobj to write*
    (void)simple_object_copy_lto_debug_sections((simple_object_read*)w, dest, &err, rename);

    return 0;
}
