#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>

int entry_func(uint64_t *lp, tmsize_t n);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 5) return 0;
    // Allocate fewer than 6 bytes so that cp[5] is out-of-bounds
    size_t sz = 5;  // concrete size per guidelines
    char *buf = (char *)malloc(sz);
    if (!buf) return 0;

    // Content can be symbolic; size remains concrete
    { memcpy(buf, fuzz_data + 0, 5); }

    tmsize_t n = 1;  // ensure the loop runs once
    entry_func((uint64_t *)buf, n);
    return 0;
}
