/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Allocate concrete png_struct and png_info using real types from harness_types.h
    png_struct *png_ptr = (png_struct*)calloc(1, sizeof(*png_ptr));
    png_info  *info_ptr = (png_info*)calloc(1, sizeof(*info_ptr));

    // Initialize some fields (not strictly needed since entry is pass-through)
    if (info_ptr) {
        // Set fields to plausible values before freeing to simulate stale pointer later
        // These values won't be used because we free the object to create UAF.
        // Still, keep them reasonable in case KLEE explores alternative paths.
        // PNG_INFO_PLTE bit set to drive the first branch if not freed
        #ifndef PNG_INFO_PLTE
        #define PNG_INFO_PLTE 0x0008u
        #endif
        info_ptr->valid = PNG_INFO_PLTE;
        info_ptr->color_type = 3; // PNG_COLOR_TYPE_PALETTE
        info_ptr->num_palette = 1;
        // Allocate a small palette to avoid null derefs if explored
        info_ptr->palette = (png_color*)calloc(1, sizeof(png_color));
    }

    // WMI-2 / UAF setup: free info_ptr to make it a stale pointer before use
    // This ensures dereferencing info_ptr->valid in png_write_info triggers free.err
    free(info_ptr);

    // Call entry (pass-through) which immediately calls png_write_info
    // info_ptr is now a dangling pointer (non-NULL stale pointer)
    png_write_png(png_ptr, (png_info*)info_ptr, 0, NULL);

    return 0;
}
