/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"
#include <stdlib.h>
#include <string.h>

int main() {
    // Prepare symbols array terminated by NULL
    struct asection *sec = (struct asection*)calloc(1, sizeof(struct asection));
    sec->vma = 0;

    asymbol *sym = (asymbol*)calloc(1, sizeof(asymbol));
    sym->name = "func";
    sym->flags = BSF_FUNCTION;   // ensure function flag
    sym->section = sec;          // non-NULL section
    sym->value = 0;

    asymbol *symbols_arr[2];
    symbols_arr[0] = sym;
    symbols_arr[1] = NULL; // terminator expected by original code
    asymbol **symbols = symbols_arr;

    // Prepare pinfo -> points to dwarf2_debug stash (as in original)
    struct dwarf2_debug *stash = (struct dwarf2_debug*)calloc(1, sizeof(struct dwarf2_debug));
    void *stash_void = (void*)stash;

    // Call entry point
    (void)_bfd_dwarf2_find_symbol_bias(symbols, &stash_void);

    return 0;
}
