#include <stdint.h>
#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for ASan concrete validation.
 * Generated by asan_replay.py from KLEE test case.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 120) return 0;
    // Allocate bfd objects
    bfd *ibfd = (bfd *)calloc(1, sizeof(bfd));
    bfd *obfd = (bfd *)calloc(1, sizeof(bfd));

    // Allocate and initialize ibfd->phdr (Elf_Internal_Phdr)
    ibfd->phdr = (Elf_Internal_Phdr *)malloc(sizeof(Elf_Internal_Phdr));
    { memcpy(ibfd->phdr, fuzz_data + 0, 64); }

    // Allocate and initialize obfd->segmap (struct elf_segment_map)
    obfd->segmap = (struct elf_segment_map *)calloc(1, sizeof(struct elf_segment_map));
    { memcpy(obfd->segmap, fuzz_data + 64, 56); }
    // Ensure next is a sane terminal pointer (avoid accidental chains)
    obfd->segmap->next = NULL;

    // Call entry function (neutralized to directly reach the vulnerable function)
    _bfd_elf_copy_private_header_data(ibfd, obfd);

    return 0;
}
